package internal.org.springframework.content.jpa.config;

import java.sql.ResultSet;
import java.sql.Statement;

import javax.persistence.EntityManager;
import javax.sql.DataSource;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.content.common.repository.factory.AbstractContentStoreFactoryBean;

import internal.org.springframework.content.jpa.repository.DefaultJpaContentRepositoryImpl;

public class JpaContentRepositoryFactoryBean extends AbstractContentStoreFactoryBean {

	@Autowired
	private EntityManager manager;
	
	@Autowired
	private DataSource datasource;
	
	@Override
	public void afterPropertiesSet() throws Exception {
		super.afterPropertiesSet();
		
		ResultSet rs = datasource.getConnection().getMetaData().getTables(null, null, "BLOBS", new String[] {"TABLE"});
		if (!rs.next()) {
			Statement stmt = datasource.getConnection().createStatement();
			String sql = "CREATE TABLE BLOBS " +
	                "(id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), " +
	                " blob BLOB, " + 
	                " PRIMARY KEY ( id ))"; 

			stmt.executeUpdate(sql);
		}
	}

	@Override
	protected Object getContentStoreImpl() {
		return new DefaultJpaContentRepositoryImpl(manager, datasource);
	}

}
