[[content-repositories]]
= Working with Spring Content Repositories

The goal of the Spring Content is to significantly reduce the amount of boilerplate code required to implement handling of rich-content resources and other media by providing content access, metadata association, search and transformation capabilities for various types of content store.

[IMPORTANT]
====
This chapter explains the core concepts and interfaces for Spring Content repositories. The information in this chapter is pulled from the Spring Content Commons. It uses the configuration and code samples for the S3 module. Adapt the Java configuration and the types to be extended to the equivalents of the particular module that you are using.
====

[[content-repositories.core-concepts]]
== Core concepts
The central interface in the Spring Content is the `ContentStore` abstraction.  This interface provides CRUD functionality and metadata association for content.  It is typed to the Spring Data domain class, with which the content will be associated, and to content ID type of that domain class. 

[[content-repositories.repository]]

.ContentRepository interface
====
[source, java]
----
public interface ContentStore<E, CID extends Serializable> {

	void setContent(E entity, InputStream content); 	<1>
	
	InputStream getContent(E entity);			<2>
	
	void unsetContent(E entity);				<3>
}
----
<1> Stores content and saves its metadata on `entity` 
<2> Returns the content associated with `entity`
<3> Deletes content and unassociates it from `entity`  
====

[[content-repositories.storage]]
=== Storage Model

Spring Content supports a pluggable storage model giving repositories the ability to store content as they see fit by making a placement service and placement service plugins available to Repositories implementations.  

In general Repository implementations use the `org.springframework.content.commons.placement.PlacementService` to map an entity's `@ContentId` to a physical storage location.

In addition a hierarchical storage model plug-in `internal.org.springframework.content.commons.UUIDPlacementStrategy` is also available to Repositories that can support this.  For example, both Spring Content Filesystem and Spring Content S3 make use this plug-in to map `java.util.UUID` content IDs to nested `org.springframework.core.io.Resource` paths.   

==== Implementation a new Storage Model plugin ====

The placement service can be extended by creating one or more `org.springframework.content.commons.placement.PlacementStrategy` beans that map other content ID types to resource locations.

[[content-repositories.events]]
=== Events
There are 6 events that Spring Content emits whilst performing basic content access.  Those are:

* BeforeSetContent

* AfterSetContent

* BeforeGetContent

* AfterGetContent

* BeforeUnsetContent

* AfterUnsetContent

==== Writing an ApplicationListener ====

There is an abstract class that you can subclass which listens for these kinds of events and calls the appropriate method based on the event type. You just override the methods for the events you’re interested in.

.AbstractContentRepositoryEventListener
====
[source, java]
----
public class ExampleEventListener extends AbstractContentRepositoryEventListener {
	
	@Override
	public void onAfterSetContent(Object entity) {
		...logic to inspect and handle the entity and it's content after it is stored
	}
	
	@Override
	public void onBeforeGetContent(Object entity) {
		...logic to inspect and handle the entity and it's content before it is fetched
	}
}
----
====
This approach does not filter events based on domain type.

==== Writing an Annotated ContentRepository Handler ====

Another approach is to use an annotated handler, which does filter events based on domain type.

To declare a handler, create a POJO and annotate it as `@ContentRepositoryEventHandler`. This tells the `BeanPostProcessor` that this class needs to be inspected for handler methods.  It iterates over the class's methods and looks for annotations that correspond to the content event. There are 6 handler annotations.  Those are:

* HandleBeforeSetContent
  
* HandleAfterSetContent

* HandleBeforeGetContent

* HandleAfterGetContent

* HandleBeforeUnsetContent

* HandleAfterUnsetContent

.Annotated event handler
====
[source, java]
----
@ContentRepositoryEventHandler
public class ExampleAnnotatedEventListener {
	
	@HandleAfterSetContent
	public void handleAfterSetContent(SopDocument doc) {
		...type-safe handling logic for SopDocument's and their content after it is stored
	}
	
	@HandleBeforeGetContent
	public void onBeforeGetContent(Product product) {
		...type-safe handling logic for Product's and their content before it is fetched
	}
}
----
====

The type of interests you are interested in is determined from the type of the first parameter of each annotated method.

To register your event handler, either mark the class with one of Spring’s @Component stereotypes so it can be picked up by @SpringBootApplication or @ComponentScan. Or declare an instance of your annotated bean in your ApplicationContext.  

.Handler registration
====
[source, java]
----
@Configuration
public class ContentRepositoryConfiguration {

  @Bean
  ExampeAnnotatedEventHandler exampleEventHandler() {
    return new ExampeAnnotatedEventHandler();
  }
}
----
====

[[content-repositories.search]]
=== Search
Applications that handle files and other media usually have search capabilities allowing content to be found by looking inside of it. 

Content repositories can therefore optionally be made searchable by extending the `Searchable<CID>` interface.

.Searchable interface
====
[source, java]
----
public interface Searchable<CID> {

    Iterable<T> findKeyword(String term);

    Iterable<T> findAllKeywords(String...terms);

    Iterable<T> findAnyKeywords(String...terms);

    Iterable<T> findKeywordsNear(int proximity, String...terms);

    Iterable<T> findKeywordStartsWith(String term);

    Iterable<T> findKeywordStartsWithAndEndsWith(String prefix, String suffix);

    Iterable<T> findAllKeywordsWithWeights(String[] terms, double[] weights);
}
----
====

[[content-repositories.renditions]]
=== Renditions
Applications that handle files and other media usually also have rendition capabilities allowing content to be transformed from one format to another.

Content repositories can therefore optionally also be given rendition capabilities by extending the `Renderable<E>` interface.

.Renderable interface
====
[source, java]
----
public interface Renderable<E> {

	InputStream getRendition(E entity, String mimeType); 
}
----
Returns a `mimeType` rendition of the content associated with `entity`.
====

[[content-repositories.creation]]
== Creating Content Repositories Instances
To use these core concepts:

. Define a Spring Data entity and give it's instances the ability to be associated with content by adding `@ContentId` and `@ContentLength` annotations
+
[source, java]
----
@Entity
public class SopDocument {
	private @Id @GeneratedValue Long id;
	private String title;
	private String[] authors, keywords;

	// Spring Content managed attribute
	private @ContentId UUID contentId;  	
	private @ContentLength Long contentLen;	
}
----

. Define an interface extending Spring Data's `CrudRepository` and type it to the domain and ID classes.
+
[source, java]
----
public interface SopDocumentRepository extends CrudRepository<SopDocument, Long> {
}
----

. Define another interface extending `ContentRepository` and type it to the domain and `@ContentId` class.
+
[source, java]
----
public interface SopDocumentContentRepository extends ContentRepository<SopDocument, UUID> {
}
----

. Optionally, make it extend `Searchable` 
+
[source, java]
----
public interface SopDocumentContentRepository extends ContentRepository<SopDocument, UUID>, Searchable<UUID> {
}
----

. Optionally, make it extend `Renderable`
+
[source, java]
----
public interface SopDocumentContentRepository extends ContentRepository<SopDocument, UUID>, Renderable<SopDocument> {
}
----
. Set up Spring to create proxy instances for these two interfaces using JavaConfig:
+
[source, java]
----
@EnableJpaRepositories
@EnableS3ContentRepositories
class Config {}
----
NOTE: The JPA and S3 namespaces are used in this example.  If you are using the repository and content repository abstraction for other database and Content stores, you need to change this to the appropriate namespace declaration for your store module. 

. Inject the repositories and use them
+
====
[source, java]
----
public class SomeClass {
	@Autowired private SopDocumentRepository repo;
  	@Autowired private SopDocumentContentRepository contentRepo;

	public void doSomething() {
	
		SopDocument doc = new SopDocument();
		doc.setTitle("example");
		contentRepo.setContent(doc, new ByteArrayInputStream("some interesting content".getBytes())); # <1>
		doc.save(); 
		...
		
		InputStream content = repository.getContent(sopDocument);
		...
		
		List<SopDocument> docs = doc.findAllByContentId(contentRepo.findKeyword("interesting"));
		...
		
	}
}
----
<1> Spring Content will update the `@ContentId` and `@ContentLength` fields
====
