[[content-repositories]]
= Working with Spring Content Repositories

The goal of the Spring Content is to significantly reduce the amount of boilerplate code required to implement handling of rich-content files and other media by providing content access, metadata association, search and transformation capabilities for various types of content store.

[IMPORTANT]
====
_Spring Content repository documentation and your module_

This chapter explains the core concepts and interfaces for Spring Content repositories. The information in this chapter is pulled from the Spring Content Commons. It uses the configuration and code samples for the S3 module. Adapt the Java configuration and the types to be extended to the equivalents of the particular module that you are using.
====

[[content-repositories.core-concepts]]
== Core concepts
The central interface in the Spring Content is the `ContentRepository` abstraction.  This interface provides CRUD functionality and metadata association for content.  It is typed to the Spring Data domain class, with which the content will be associated, and to content id type of that domain class. 

[[content-repositories.repository]]

.ContentRepository interface
====
[source, java]
----
public interface ContentRepository<E, CID extends Serializable> {

	void setContent(E entity, InputStream content); 	<1>
	
	InputStream getContent(E entity);			<2>
	
	void unsetContent(E entity);				<3>
}
----
<1> Stores content and saves its metadata on `entity` 
<2> Returns the content associated with `entity`
<3> Deletes content and unassociates it from `entity`  
====

[[content-repositories.search]]
=== Search
Applications that handle files and other media usually have search capabilities allowing content to be found by looking inside of it. 

Content repositories can therefore optionally be made searchable by extending the `Searchable<CID>` interface.

[source, java]
----
public interface Searchable<CID> {

    Iterable<T> findKeyword(String term);

    Iterable<T> findAllKeywords(String...terms);

    Iterable<T> findAnyKeywords(String...terms);

    Iterable<T> findKeywordsNear(int proximity, String...terms);

    Iterable<T> findKeywordStartsWith(String term);

    Iterable<T> findKeywordStartsWithAndEndsWith(String prefix, String suffix);

    Iterable<T> findAllKeywordsWithWeights(String[] terms, double[] weights);
}
----

[[content-repositories.search]]
=== Renditions
Applications that handle files and other media usually also have rendition capabilities allowing content to be transformed from one format to another.

Content repositories can therefore optionally also be given rendition capabilities by extending the `Renderable<E>` interface.

[source, java]
.Renderable interface
----
public interface Renderable<E> {

	InputStream getRendition(E entity, String mimeType); 
}
----
- Returns a `mimeType` rendition of the content associated with `entity`

[[content-repositories.creation]]
== Creating Content Repositories Instances
To use these core concepts:

. Define a Spring Data entity and associate it with content using content annotations
+
[source, java]
----
@Entity
public class SopDocument {
	private @Id @GeneratedValue Long id;
	private String title;
	private String[] authors, keywords;

	// Spring Content managed attribute
	private @ContentId UUID contentId;  	
	private @ContentLength Long contentLen;	
}
----

. Define an interface extending Spring Data's `CrudRepository` and type it to the domain and ID classes.
+
[source, java]
----
public interface SopDocumentRepository extends CrudRepository<SopDocument, Long> {
}
----

. Define another interface extending `ContentRepository` and type it to the domain and `@ContentId` class.
+
[source, java]
----
public interface SopDocumentContentRepository extends ContentRepository<SopDocument, UUID> {
}
----

. Optionally, make it extend `Searchable` 
+
[source, java]
----
public interface SopDocumentContentRepository extends ContentRepository<SopDocument, UUID>, Searchable<UUID> {
}
----

. Optionally, make it extend `Renderable`
+
[source, java]
----
public interface SopDocumentContentRepository extends ContentRepository<SopDocument, UUID>, Renderable<SopDocument> {
}
----
. Set up Spring to create proxy instances for these two interfaces using JavaConfig:
+
[source, java]
----
@EnableJpaRepositories
@EnableS3ContentRepositories
class Config {}
----
- The JPA and S3 namespaces are used in this example.  If you are using the repository and content repository abstraction for other database and Content stores, you need to change this to the appropriate namespace declaration for your store module. 

. Inject the repositories and use them
+
[source, java]
----
public class SomeClass {
	@Autowired private SopDocumentRepository repo;
  	@Autowired private SopDocumentContentRepository contentRepo;

	public void doSomething() {
		SopDocument doc = new SopDocument();
		doc.setTitle("example");
		contentRepo.setContent(doc, new ByteArrayInputStream("some example content".getBytes()));
		doc.save(); 
		...
		InputStream content = repository.getContent(sopDocument);
	}
}
----
- Spring Content will update the `@ContentId` and `@ContentLength` fields
