= MongoDB Content Repositories

== Annotation based configuration

Spring Content MongoDB repositories are enabled with the following Java Config.

.Spring Content MongoDB repositories using Java Config
====
[source, java]
----
@Configuration
@EnableMongoContentRepositories
public static class ApplicationConfig extends AbstractMongoConfiguration { <1> 

  	@Override
  	protected String getDatabaseName() {
  		return "database";
  	}

	@Override
  	public Mongo mongo() throws Exception {
  		return new Mongo();
  	}

	@Bean
	public GridFsTemplate gridFsTemplate() throws Exception {			<2>
		return new GridFsTemplate(mongoDbFactory(), mappingMongoConverter());
	}
	
}
----
<1> For ease of use we extend Spring Data MongoDB's `AbstractMongoConfiguration` to set the container up for all of the required foundational MongoDB beans
<2> In addition we add MongoDB's `GridFsTemplate` bean
====

== Accessing Content

=== Setting Content

Storing content is achieved using the `ContentRepostory.setContent(entity, InputStream)` method.  

The fields annotated with @ContentId and @ContentLength will be updated on `entity`.  

If content has been previously stored it will overwritten updating just the @ContentLength attribute, if appropriate.

==== How the @ContentId field is handled 

Spring Data MongoDB requires that content entities have an `@ContentId` field for identity.  If you do not provide a value for this field one will be generated based on `java.util.UUID`.  

=== Getting Content

Content can be accessed using the `ContentRepository.getContent(entity)` method.  

=== Unsetting Content

Content can be removed using the `ContentRepository.unsetContent(entity)` method.

When content is unset the fields annotated with @ContentId and @ContentLength will also be reset to default values; 
