= MongoDB Content Stores

== Maven Central Coordinates
The maven coordinates for this Spring Content library are as follows:
```xml
<dependency>
    <groupId>com.github.paulcwarren</groupId>
    <artifactId>spring-content-mongo</artifactId>
</dependency>
```

As it is usual to use several Spring Content libraries together importing the bom is recommended:
```xml
<dependency>
    <groupId>com.github.paulcwarren</groupId>
    <artifactId>spring-content-bom</artifactId>
    <version>${spring-content-version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
```

== Annotation based configuration

Spring Content MongoDB Stores are enabled with the following Java Config.

.Spring Content MongoDB Stores using Java Config
====
[source, java]
----
@Configuration
@EnableMongoContentRepositories
public static class ApplicationConfig extends AbstractMongoConfiguration { <1> 

  	@Override
  	protected String getDatabaseName() {
  		return "database";
  	}

	@Override
  	public Mongo mongo() throws Exception {
  		return new Mongo();
  	}

	@Bean
	public GridFsTemplate gridFsTemplate() throws Exception {			<2>
		return new GridFsTemplate(mongoDbFactory(), mappingMongoConverter());
	}
	
}
----
<1> For ease of use we extend Spring Data MongoDB's `AbstractMongoConfiguration` to set the container up for all of the required foundational MongoDB beans
<2> In addition we add MongoDB's `GridFsTemplate` bean
====

== Accessing Content

=== Signature Types
[[signature_types]]

Mongo's GridFS Storage supports the following signature types:

- `org.springframework.content.mongo.store.MongoContentStore`

The module id for the `spring.content.storage.type.default` property is `gridfs`.

=== Setting Content

Storing content is achieved using the `ContentStore.setContent(T entity, PropertyPath path, InputStream content, SetContentParams params)` method.

The `PropertyPath` will be used to resolve the content property to update.

If content has not yet been stored with this entity and an Id has not been assigned, one will be generated based in `java.util.UUID`.

The `@ContentId` and `@ContentLength` annotations will be updated on `entity`.

If content has previously been stored it will be overwritten also updating the @ContentLength attribute, if present.  However, using `ContentDisposition.Create` on the `SetContentParams` a new Id will be assigned and content stored, leaving the existing content in place and orphaned.

=== Getting Content

Content can be accessed using the `ContentStore.getContent(T entity, PropertyPath path)` method.

=== Unsetting Content

Content can be removed using the `ContentStore.unsetContent(T entity, PropertyPath path, UnsetContentParams params)` method.  Using `ContentDisposition.Keep` on `UnsetContentParams` will leave the content in storage and orphaned.
