= MongoDB Content Stores

== Annotation based configuration

Spring Content MongoDB Stores are enabled with the following Java Config.

.Spring Content MongoDB Stores using Java Config
====
[source, java]
----
@Configuration
@EnableMongoContentRepositories
public static class ApplicationConfig extends AbstractMongoConfiguration { <1> 

  	@Override
  	protected String getDatabaseName() {
  		return "database";
  	}

	@Override
  	public Mongo mongo() throws Exception {
  		return new Mongo();
  	}

	@Bean
	public GridFsTemplate gridFsTemplate() throws Exception {			<2>
		return new GridFsTemplate(mongoDbFactory(), mappingMongoConverter());
	}
	
}
----
<1> For ease of use we extend Spring Data MongoDB's `AbstractMongoConfiguration` to set the container up for all of the required foundational MongoDB beans
<2> In addition we add MongoDB's `GridFsTemplate` bean
====

== Accessing Content

=== Setting Content

Storing content is achieved using the `ContentStore.setContent(entity, InputStream)` method.  

The fields annotated with @ContentId and @ContentLength will be updated on `entity`.  

If content has been previously stored it will overwritten updating just the @ContentLength attribute, if appropriate.

==== How the @ContentId field is handled 

The MongoDB Store uses a dedicated `ConversionService` to convert the content entity's ID into a resource path.  

It is possible to influence this conversion and therefore the storage model by configuring your application to contribute one (or more) `org.springframework.content.mongo.config.MongoStoreConverter` beans.  

=== Getting Content

Content can be accessed using the `ContentStore.getContent(entity)` method.  

=== Unsetting Content

Content can be removed using the `ContentStore.unsetContent(entity)` method.

When content is unset the fields annotated with @ContentId and @ContentLength will also be reset to default values; 
