= S3 Content Stores

== Annotation based configuration

Spring Content S3 is enabled with the following Java Config.

.Enabling Spring Content S3 using Java Config
====
[source, java]
----
@Configuration
@EnableS3Stores
public static class ApplicationConfig {
	
	@Bean
	public AmazonS3 client() {	<1>
		BasicAWSCredentials creds = new BasicAWSCredentials(...)
		AmazonS3Client amazonS3Client = new AmazonS3Client(creds);
		return amazonS3Client;
	}
    
	@Bean
	public SimpleStorageResourceLoader simpleStorageResourceLoader(AmazonS3 client) {	<2>
		return new SimpleStorageResourceLoader(client);
	}
	
}
----
<1> The Amazon S3 client used by the S3 ResourceLoader
<2> The S3 ResourceLoader used by the S3 Store
====

== Configuring

The following configuration properties (prefix `spring.content.s3`) are supported.

[cols="3*", options="header"]
|=========
| Property | Required | Description
| bucket | No | Content store location.  If not set as an application property Spring Content S3 will look for  the environment variable AWS_BUCKET
|=========

== Accessing Content

=== Storage Model

In Amazon S3, buckets and objects are the primary resources, where objects are stored in buckets.  Amazon S3 has a flat
structure with no hierarchy like you would see in a typical file system.  There are also no limits to the number of
buckets and objects in buckets.  However, for the sake of organizational simplicity, the Amazon S3 console supports
the folder concept as a means of grouping objects. Amazon S3 does this by using key name prefixes for objects.

Spring Content S3's default behavior is to store content in a single bucket.  Determined by the `spring.content.s3.bucket`
property or `AWS_BUCKET` environment variable.

If you wish to store your content in different buckets.  For example, one bucket per tenant or customer.  You can use the
`org.springframework.s3.S3ContentId` class as the Store's ID type.  This captures the content's bucket as part of its
identity.  However, this type is not a managed ID type and must therefore be managed by the application.

S3 Stores will store all content in a flat structure by using the content ID as the object key.

A dedicated `ConversionService` can be used to convert the content ID from one type to another. By contributing a
`org.springframework.core.convert.converter.Converter` bean to convert content ID to folder path locations it is
possible to configure the Store to take advantage of S3's console folder concepts.

For example content IDs of type `java.util.UUID` or `java.net.URI` can both be mapped to a path that will have the
effect, in the Amazon S3 console, of organizing content into a distributed set of folders.
 
.Configuring the S3 Store  
====
[source, java]
----
@Configuration
public class S3StoreConfiguration  {

	public Converter<UUID,String> converter() {
		return new S3StoreConverter<String,String>() {

			@Override
			public String convert(UUID source) {
				return String.format("/%s", source.toString().replaceAll("-", "/"));
			}
		};
	}
	
	@Bean
	public S3StoreConfigurer configurer() {
		return new S3StoreConfigurer() {

			@Override
			public void configureS3StoreConverters(ConverterRegistry registry) {
				registry.addConverter(converter());
			}
		};
	}
}
----
====  

=== Setting Content

Storing content is achieved using the `ContentStore.setContent(entity, InputStream)` method.  

If content has not yet been stored with this entity before and an ID has not been assigned one will be generated based
in `java.util.UUID`.

The @ContentId and @ContentLength annotations will be updated on `entity`.  

If content has been previously stored it will overwritten updating just the @ContentLength attribute, if appropriate.

=== Getting Content

Content can be accessed using the `ContentStore.getContent(entity)` method.  

=== Unsetting Content

Content can be removed using the `ContentStore.unsetContent(entity)` method.
