= S3 Content Repositories

== Annotation based configuration

Spring Content S3 is enabled with the following Java Config.

.Enabling Spring Content S3 using Java Config
====
[source, java]
----
@Configuration
@EnableS3ContentRepositories
public static class ApplicationConfig extends AbstractS3ContentRepositoryConfiguration {
	
	@Autowired
	private AmazonS3 client;

	@Override
	public SimpleStorageResourceLoader simpleStorageResourceLoader() {	<1>
		client.setRegion(RegionUtils.getRegion("us-west-1"));
		return new SimpleStorageResourceLoader(client);
	}
}
----
<1> The S3 resource loader that will be used by the S3 Content Store
====

== Configuring

The following configuration properties (prefix `spring.content.s3`) are supported.

[cols="2*", options="header"]
|=========
| Property | Required | Description
| bucket | Yes | Content store location.  If not set as an application property Spring Content S3 will look for  the environment variable AWS_BUCKET   
|=========

== Accessing Content

=== Storage Model 

In order to store as much content as possible in the bucket Spring Content S3 supports a hierarchical storage model.  

Content IDs of type `java.util.UUID` are mapped to a nested resource path which has the effect of distributing content evenly throughout the bucket. 

Additional storage models and Content ID types can be added by creating  `org.springframework.content.commons.placement.PlacementService` plug-ins.  See <<content-repositories.storage,Storage Model>>.   

=== Setting Content

Storing content is achieved using the `ContentRepostory.setContent(entity, InputStream)` method.  

If content has not yet been stored with this entity before and an ID has not been assigned one will be generated.  

From this ID the `PlacementService` will then be used to determine the physical storage location and the content will be stored.

The @ContentId and @ContentLength annotations will be updated on `entity`.  

If content has been previously stored it will overwritten updating just the @ContentLength attribute, if appropriate.

=== Getting Content

Content can be accessed using the `ContentRepository.getContent(entity)` method.  

=== Unsetting Content

Content can be removed using the `ContentRepository.unsetContent(entity)` method.
