= S3 Content Repositories

== Annotation based configuration

Spring Content S3 is enabled with the following Java Config.

.Enabling Spring Content S3 using Java Config
====
[source, java]
----
@Configuration
@EnableS3ContentRepositories
public static class ApplicationConfig extends AbstractS3ContentRepositoryConfiguration {
	
	@Autowired
	private AmazonS3 client;

	@Override
	public SimpleStorageResourceLoader simpleStorageResourceLoader() {	<1>
		client.setRegion(RegionUtils.getRegion("us-west-1"));
		return new SimpleStorageResourceLoader(client);
	}
}
----
<1> The S3 resource loader that will be used by the S3 Content Store
====

== Configuring

The following configuration properties (prefix `spring.content.s3`) are supported.

[cols="2*", options="header"]
|=========
| Property | Required | Description
| bucket | Yes | Content store location.  If not set as an application property Spring Content S3 will look for  the environment variable AWS_BUCKET   
|=========

== Accessing Content

=== Storage Model 

In Amazon S3, buckets and objects are the primary resources, where objects are stored in buckets.  Amazon S3 has a flat structure with no hierarchy like you would see in a typical file system.  There are also no limits to the number of buckets and objects in buckets.  However, for the sake of organizational simplicity, the Amazon S3 console supports the folder concept as a means of grouping objects. Amazon S3 does this by using key name prefixes for objects.

Accordingly by default Spring Content S3 will store content entities in the root of the store's bucket using the @ContentId field value as the key.  

If you wish to take advantage of S3's console folder concept you can create your content entities with hierarchical @ContentId field types like `java.net.URI` or field types that can be mapped to a hierarchy like `java.util.UUID` and create a corresponding `org.springframework.content.commons.placement.PlacementStrategy`.  See <<content-repositories.storage,Storage Model>> for more information.   

=== Setting Content

Storing content is achieved using the `ContentRepostory.setContent(entity, InputStream)` method.  

If content has not yet been stored with this entity before and an ID has not been assigned one will be generated based in `java.util.UUID`.  

The @ContentId and @ContentLength annotations will be updated on `entity`.  

If content has been previously stored it will overwritten updating just the @ContentLength attribute, if appropriate.

=== Getting Content

Content can be accessed using the `ContentRepository.getContent(entity)` method.  

=== Unsetting Content

Content can be removed using the `ContentRepository.unsetContent(entity)` method.
