= S3 Content Stores

== Annotation based configuration

Spring Content S3 is enabled with the following Java Config.

.Enabling Spring Content S3 using Java Config
====
[source, java]
----
@Configuration
@EnableS3Stores
public static class ApplicationConfig {
	
	@Bean
	public AmazonS3 client() {	<1>
		BasicAWSCredentials creds = new BasicAWSCredentials(...)
		AmazonS3Client amazonS3Client = new AmazonS3Client(creds);
		return amazonS3Client;
	}
    
	@Bean
	public SimpleStorageResourceLoader simpleStorageResourceLoader(AmazonS3 client) {	<2>
		return new SimpleStorageResourceLoader(client);
	}
	
}
----
<1> The Amazon S3 client used by the S3 ResourceLoader
<2> The S3 ResourceLoader used by the S3 Store
====

== Configuring

The following configuration properties (prefix `spring.content.s3`) are supported.

[cols="3*", options="header"]
|=========
| Property | Required | Description
| bucket | Yes | Content store location.  If not set as an application property Spring Content S3 will look for  the environment variable AWS_BUCKET   
|=========

== Accessing Content

=== Storage Customization

In Amazon S3, buckets and objects are the primary resources, where objects are stored in buckets.  Amazon S3 has a flat structure with no hierarchy like you would see in a typical file system.  There are also no limits to the number of buckets and objects in buckets.  However, for the sake of organizational simplicity, the Amazon S3 console supports the folder concept as a means of grouping objects. Amazon S3 does this by using key name prefixes for objects.  Accordingly, by default, Spring Content S3 will store all content at the root of the content store location.  

However, the S3 Store uses a dedicated `ConversionService` to convert the content entity's ID into a resource path.  By configuring your application to contribute one (or more) instances of `org.springframework.core.concert.converter.Converter` it is possible to configure the Store to take advantage of S3's console folder concepts. 

For example Content IDs of type `java.util.UUID` or `java.net.URI` can both be mapped to a nested resource path that will have the effect in the Amazon S3 console of organizing content into a distributed set of folders.       
 
.Configuring the S3 Store  
====
[source, java]
----
@Configuration
public class S3StoreConfiguration  {

	public Converter<String,String> converter() {
		return new S3StoreConverter<String,String>() {

			@Override
			public String convert(String source) {
				return String.format("/%s", source.replaceAll("-", "/"));
			}
		};
	}
	
	@Bean
	public S3StoreConfigurer configurer() {
		return new S3StoreConfigurer() {

			@Override
			public void configureS3StoreConverters(ConverterRegistry registry) {
				registry.addConverter(converter());
			}
		};
	}
}
----
====  

=== Storage Model 


Accordingly by default Spring Content S3 will store content entities in the root of the store's bucket using the @ContentId field value as the key.  

If you wish to take advantage of S3's console folder concept you can create your content entities with hierarchical @ContentId field types like `java.net.URI` or field types that can be mapped to a hierarchy like `java.util.UUID` and create a corresponding `org.springframework.content.commons.placement.PlacementStrategy`.  See <<content-repositories.storage,Storage Model>> for more information.   

=== Setting Content

Storing content is achieved using the `ContentStore.setContent(entity, InputStream)` method.  

If content has not yet been stored with this entity before and an ID has not been assigned one will be generated based in `java.util.UUID`.  

The @ContentId and @ContentLength annotations will be updated on `entity`.  

If content has been previously stored it will overwritten updating just the @ContentLength attribute, if appropriate.

=== Getting Content

Content can be accessed using the `ContentStore.getContent(entity)` method.  

=== Unsetting Content

Content can be removed using the `ContentStore.unsetContent(entity)` method.
