= S3 Content Stores

== Maven Central Coordinates
The maven coordinates for this Spring Content library are as follows:
```xml
<dependency>
    <groupId>com.github.paulcwarren</groupId>
    <artifactId>spring-content-s3</artifactId>
</dependency>
```

As it is usual to use several Spring Content libraries together importing the bom is recommended:
```xml
<dependency>
    <groupId>com.github.paulcwarren</groupId>
    <artifactId>spring-content-bom</artifactId>
    <version>${spring-content-version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
```

== Annotation based configuration

Spring Content S3 is enabled with the following Java Config.

.Enabling Spring Content S3 using Java Config
====
[source, java]
----
@Configuration
@EnableS3Stores
public static class ApplicationConfig {

	@Bean
	public S3Client client() {	<1>
        Region region = Region.US_WEST_2;
        return S3Client.builder()
                .region(region)
                .build();
    }
}
----
<1> The S3Client bean used by the S3 ResourceLoader
<2> A default bucket also needs to be set (see Configuring below)
====

== Configuring

The following configuration properties (prefix `spring.content.s3`) are supported.

[cols="3*", options="header"]
|=========
| Property | Required | Description
| bucket | No | Content store location.  If not set as an application property Spring Content S3 will look for  the environment variable AWS_BUCKET
|=========

== Accessing Content

=== Signature Types
[[signature_types]]

S3 Storage supports the following signature types:

- `org.springframework.content.s3.store.S3ContentStore`

The module id for the `spring.content.storage.type.default` property is `s3`.

=== Multi-tenancy

Contributing an S3Client bean (as described above) to use as the connection to your amazon account is usually
sufficient for most use cases.  However, for the times when you need to dynamically determine the connection based on
runtime context you can contribute a `MultiTenantS3ClientProvider` bean, as follows:

.Enabling Spring Content S3 using Java Config
====
[source,java]
----
import org.springframework.content.s3.config.MultiTenantS3ClientProvider;
@Configuration
@EnableS3Stores
public static class ApplicationConfig {

	@Bean
	public MultiTenantS3ClientProvider s3Provider() {
		return new MultiTenantS3ClientProvider() {
            @Override
            public S3Client getS3Client() {
                /*your implementation*/
            }
        };
    }
}
----
====

The S3Store will provide the S3Client object returned by this function to any `Resource`s that it is asked to
load.

=== Storage Model

In Amazon S3, buckets and objects are the two main primitives, where objects are stored in buckets.  Amazon S3 has a
flat structure with no hierarchy like you would see in a typical file system.  There are also no limits to the number
of buckets or objects in buckets.  However, for the sake of organizational simplicity, the Amazon S3 console supports
the folder concept as a means of grouping objects. Amazon S3 does this by using key name prefixes for objects.

=== S3ObjectId Resolution

Before content is stored or retrieved the store uses the following rules to determine the bucket and
key to create an `S3ObjectId`.

For `Store`:

- if the ID is already an `S3ObjectId` this will be used as-is
- otherwise, if a registered Spring Converter exists that converts the ID to an `S3ObjectId` this will be used to create
an `S3ObjectId`
- otherwise, the `@ContentId` field and default bucket will be used as key and bucket respectively to create an
`S3Object`

For `AssociativeStore` or `ContentStore`:

- if a registered Spring Converter exists that converts the entity to an `S3ObjectId` this will be used
- otherwise, if one of the Entity's field is annotated with `@Bucket`, the `@ContentId` and the `@Bucket` will be used as
key and bucket respectively to create a new `S3ObjectId`
- otherwise, the `@ContentId` field and default bucket will be used as key and bucket respectively to create an
`S3Object`

===== Configuring a Spring Converter

To configure Spring Content S3 with one or more Spring Converters that convert your Entities, or IDs, to an
instance of S3ObjectId the following approach can be used:

.Configuring Spring Content S3 with a custom Spring Converter
====
[source, java]
----
@Configuration
public class S3StoreConfiguration  {

	@Bean
	public S3StoreConfigurer configurer() {
        return new S3StoreConfigurer() {

            @Override
            public void configureS3StoreConverters(ConverterRegistry registry) {
                registry.addConverter(new Converter<TestEntity, S3ObjectId>() {
                    @Override
                    public S3ObjectId convert(TestEntity entity) {
                        return new S3ObjectId(entity.getCustomBucketField(), entity.getCustomContentIdField());
                    }
                });
            }


            @Override
            public void configureS3ObjectIdResolvers(S3ObjectIdResolvers resolvers) {
                // deprecated
            }
        }
	}
}
----
====

==== Key Resolution

By default, Spring Content S3 will store all content using simple keys.  This maps well onto primitive datatypes and
`java.util.UUID`.

The S3 Store uses a `PlacementService` to convert the Entity's `@ContentId` into a resource path string.  By
configuring your application to contribute one (or more) Spring Converters that convert from your Entity's ID to String
it is possible to configure the Store to take advantage of S3's console folder concepts.

For example, `@ContentId` fields of type `java.util.UUID` or `java.net.URI` can both be mapped to a nested resource path
that will have the effect, in the Amazon S3 console, of organizing content into a distributed set of folders.

.Configuring the S3 Store with a custom converter
====
[source, java]
----
@Configuration
public class S3StoreConfiguration  {

	@Bean
	public S3StoreConfigurer configurer() {
        return new S3StoreConfigurer() {

            @Override
            public void configureS3StoreConverters(ConverterRegistry registry) {

                registry.addConverter(new Converter<UUID,String>() {
                    @Override
                    public String convert(UUID source) {
                        return String.format("/%s", source.toString().replaceAll("-", "/"));
                    }
                });
            }

            @Override
            public void configureS3ObjectIdResolvers(S3ObjectIdResolvers resolvers) {
                // deprecated
            }
        }
	}
}
----
====

=== Setting Content

Storing content is achieved using the `ContentStore.setContent(T entity, PropertyPath path, InputStream content, SetContentParams params)` method.

The `PropertyPath` will be used to resolve the content property to update.

If content has not yet been stored with this entity and an Id has not been assigned, one will be generated based in `java.util.UUID`.

The `@ContentId` and `@ContentLength` annotations will be updated on `entity`.

If content has previously been stored it will be overwritten also updating the @ContentLength attribute, if present.  However, using `ContentDisposition.Create` on the `SetContentParams` a new Id will be assigned and content stored, leaving the existing content in place and orphaned.

=== Getting Content

Content can be accessed using the `ContentStore.getContent(T entity, PropertyPath path)` method.

=== Unsetting Content

Content can be removed using the `ContentStore.unsetContent(T entity, PropertyPath path, UnsetContentParams params)` method.  Using `ContentDisposition.Keep` on `UnsetContentParams` will leave the content in storage and orphaned.
