= Content Encryption

== Maven Central Coordinates
The maven coordinates for this Spring Content library are as follows:
```xml
<dependency>
    <groupId>com.github.paulcwarren</groupId>
    <artifactId>spring-content-encryption</artifactId>
</dependency>
```

As it is usual to use several Spring Content libraries together importing the bom is recommended:
```xml
<dependency>
    <groupId>com.github.paulcwarren</groupId>
    <artifactId>spring-content-bom</artifactId>
    <version>${spring-content-version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
```

== Adding Encryption to your ContentStores

Spring Content Encryption adds the interface `EncryptingContentStore` that can be used to decorate a `Store`
to provide at-rest encryption of the content in that Store.

This module uses an envelope encryption strategy.  Envelope encryption is the practice of encrypting content
with a content-encryption key, and then encrypting the content-encryption key under another key.

Every time
content is stored it is first encrypted using the AES-CTR cipher and a randomly generated key.  That
content-encryption key is then (optionally) encrypted using a different key-encryption method and the encrypted content-encryption key
is then storied on the domain object.  Any user with authorization to decrypt the content-encryption key can retrieve the content.

Spring Content Encryption can be added to your application by adding the dependency:

====
[source, xml]
----
<dependency>
    <groupId>com.github.paulcwarren</groupId>
    <artifactId>spring-content-encryption</artifactId>
    <version>${spring-content-version}</version>
</dependency>
----
====

and then updating your application's configuration, as follows:

.Spring Content Encryption using Java Config
====
[source, java]
----
@Configuration
@EnableFilesystemStores
public static class Config {

    @Bean
    public EncryptingContentStoreConfigurer<FileContentStore> config() {                              (1)
        return new EncryptingContentStoreConfigurer<FileContentStore>() {
            @Override
            public void configure(EncryptingContentStoreConfiguration<FileContentStore> config) {
                config.encryptionKeyContentProperty("key");
            }
        };
    }
}
----
1. The `config` configures the encryption for the `FileContentStore` with the property to use to store the encryption key
====

Domain objects content properties are then updated with a custom attribute to store the encrypted content-encryption key.

The above example assumes you have defined a "key" attribute on the content property, as the following example shows:

.Domain Object Content Property
====
[source, java]
----
@Entity
@Getter
@Setter
@NoArgsConstructor
public static class File {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    ...other properties...

    @ContentId private UUID contentId;
    @ContentLength private long contentLength;
    @MimeType private String contentMimeType;
    @JsonIgnore private byte[] contentKey;                          (1)
}
----
1. The additional "custom" attribute `key` that will be used to store the encrypted content encryption key
====

Lastly, the Store is decorated with the interface `EncryptingContentStore`.

.Decorated Store Interface
====
[source, java]
----
public interface FileContentStore extends ContentStore<File, UUID>, EncryptingContentStore<File, UUID> {}
----
====

=== Content Encryption components

There are 3 separate components that work together to provide content encryption:

1. `ContentEncryptionEngine`: Performs encryption/decryption of the content itself with a content-encryption key
2. `DataEncryptionKeyWrapper`: Performs wrapping (encryption) and unwrapping (decryption) of the content-encryption key
3. `DataEncryptionKeyAccessor`: Stores and retrieves the encrypted content-encryption key

All components of the content encryption system can be configured or swapped out with custom implementations to suit your particular needs.

.Spring Content Encryption configuration
====
[source,java]
----
@EnableFilesystemStores
public static class Config {

    @Bean
    VaultDataEncryptionKeyWrapper vaultDataEncryptionKeyWrapper(VaultOperations vault) {
        return new VaultDataEncryptionKeyWrapper(vault);
    }

    @Bean
    public EncryptingContentStoreConfigurer<FileContentStore> config(VaultDataEncryptionKeyWrapper keyWrapper) {
        return new EncryptingContentStoreConfigurer<FileContentStore>() {
            @Override
            public void configure(EncryptingContentStoreConfiguration<FileContentStore> config) {
                config.encryptionKeyContentProperty("key")                                          (1)
                    .contentEncryptionMethod(ContentEncryptionMethod.AES_CTR_256)                   (2)
                    .dataEncryptionKeyWrappers(List.of(keyWrapper))                                 (3)
                    ;
            }
        };
    }
}
----
1. Configures the `FileContentStore` with the property to use to store the encryption key
2. Use AES-CTR with 256 bit keys for encrypting content
3. Use Hashicorp Vault to wrap (encrypt) the content-encryption key
====

== Byte-Range Support

Support for byte-range requests is dependent on the encryption algorithm that is used for content encryption.

The default implementation using AES-CTR is capable of serving byte-ranges.
However, it depends on the type of backing storage how that happens exactly.

With S3 storage byte-ranges will be forwarded onto S3 for fetching and therefore only the
byte range need be decrypted before serving.  This is very efficient.

With storage that does not yet support byte ranges.  Filesystem for example.  The
byte range cannot be forwarded and the entire content is fetched and decrypted before
serving just the byte range.  This is less efficient but works and can be useful when, for
example, S3 storage is used in production, but filesystem is used in test.

== Getting Started
For a working example please refer to the getting started guide link:http://https://paulcwarren.github.io/spring-content/spring-content-with-encryption-docs/[here].