[[fulltext-search]]
= Fulltext Indexing and Searching with Elasticsearch

== Overview

When enabled, the Elasticsearch integration will forward all content to an Elasticsearch cluster for fulltext indexing.

== Annotation-based Configuration

Spring Content Elasticsearch requires a `RestHighLevelClient` bean that is used as the connection to the Elasticsearch
cluster that you wish to use for indexing.

Elasticsearch is enabled with the following Java Config.

.Enabling Spring Content Elasticsearch with Java Config
====
[source, java]
----
@Configuration
@EnableElasticsearchFulltextIndexing        <1>
@EnableFilesystemStores                     <2>
public static class ApplicationConfig {

                                            <3>
    public RestHighLevelClient client() {
        return new RestHighLevelClient(RestClient.builder(new HttpHost("localhost", 9200, "http")));
    }

}
----
1. Specify the `@EnableElasticsearchFulltextIndexing` annotation in an `@Configuration` class
2. Spring Content Elasticsearch works with any Spring Content Store module
3. Ensure a `RestHighLevelClient` bean is instantiated somewhere within your `@Configuration`
====

== Making Stores Searchable

With fulltext-indexing enabled, Store interfaces can be made `Searchable`.  See
<<content-repositories.search,Searchable Stores>> for more information on how to do this.

== Text Extraction

For images and other media, it also possible to configure the elasticsearch integration 
to perform text extraction and send that instead of the image content to elasticsearch.

This requires two stages of configuration:

* Add one or more renderers to the application context.  These renderers 
are used to perform the text extraction.  The renderer *must* produce the mimetype 
`text/plain` and will be invoked by the elasticsearch indexer when content matching 
their "consume" mime-type is added.

.Adding a renderer to perform text extraction
====
[source, java]
----
@Configuration
@EnableElasticsearchFulltextIndexing
@EnableFilesystemStores
public static class ApplicationConfig {

    public RestHighLevelClient client() {
        return new RestHighLevelClient(RestClient.builder(new HttpHost("localhost", 9200, "http")));
    }
    
    @Bean
    public RenditionProvider jpgTextExtractor() {
        return new RenditionProvider() {
            
            @Override
            public String consumes() {
                return "image/jpg";
            }

            @Override
            public String[] produces() {
                return new String[] {"text/plain"};
            }

            @Override
            public InputStream convert(InputStream fromInputSource, String toMimeType) {
                ...implementation...
            }
        }
    }
}
====

* Make the Store Renderable

.Making the Store interface Renderable
====
[source, java]
----
public interface DocumentStore extends ContentStore<Document, UUID> implements Searchable<Document>, Renderable<Document> {
}
====

