= Azure Storage

== Maven Central Coordinates
The maven coordinates for this Spring Content library are as follows:
```xml
<dependency>
    <groupId>com.github.paulcwarren</groupId>
    <artifactId>spring-content-azure-storage</artifactId>
</dependency>
```

As it is usual to use several Spring Content libraries together importing the bom is recommended:
```xml
<dependency>
    <groupId>com.github.paulcwarren</groupId>
    <artifactId>spring-content-bom</artifactId>
    <version>${spring-content-version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
```

== Annotation-based Configuration

Spring Content Azure Storage is enabled with the following Java Config.

.Enabling Spring Content Azure using Java Config
====
[source, java]
----
@Configuration
@EnableAzureStorage
public static class ApplicationConfig {

        @Value("#{environment.AZURE_STORAGE_ENDPOINT}")
        private String endpoint;

        @Value("#{environment.AZURE_STORAGE_CONNECTION_STRING}")
        private String connString;

        @Bean
        public BlobServiceClientBuilder storage() {
                return new BlobServiceClientBuilder()
                .endpoint(endpoint)
                .connectionString(connString);
        }
}
----
====

== Configuration Properties

The following configuration properties (prefix `spring.content.azure`) are supported.

[cols="3*", options="header"]
|=========
| Property | Required | Description
| bucket | No | Content store location.  If not set as an application property Spring Content Azure Storage will look for  the environment variable `AZURE_STORAGE_BUCKET`
|=========

== Accessing Content

=== Signature Types
[[signature_types]]

Azure Storage supports the following signature types:

- `org.springframework.content.azure.store.AzureStorageContentStore`

The module id for the `spring.content.storage.type.default` property is `azs`.

=== Storage Model

With Azure Blob Storage, buckets and objects are the two main primitives, where objects are stored in buckets.  Azure has a
flat structure with no hierarchy like you would see in a typical file system.  There are also no limits to the number
of buckets or objects in buckets.  

=== Loading Spring Resources from a Store or AssociativeStore

When a Resource is loaded from the Store the following rules are used to determine the identify the `BlobId` of the
object.

For a `Store`, when a Resource is loaded using a call to `getResource(ID location)`.

- if the Store is typed to a `BlobId` this will be used as-is.
- otherwise, if a registered Spring Converter exists that converts from Store's ID type to a `BlobId` this 
will be used to convert the location (specified in the call to `getResource`) into an instance of `BlobId`
- otherwise, a `BlobId` is created from the default bucket and the location (specified in the call to `getResource`).

For an `AssociativeStore` (or indirectly a `ContentStore`), when a Resource is loaded from a call to `getResource(S entity)`:

- if the store's ID type is typed to a `BlobId` this will be used as-is
- otherwise, if a registered Spring Converter exists that converts the the Store's entity (S) type to a `BlobId` this will be used
to establish an instance of `BlobId`
- otherwise, if one of the Entity's fields is annotated with `@Bucket`, the `@ContentId` and the `@Bucket` will be used as
name and bucket respectively to create an instance of `BlobId`
- otherwise, the `@ContentId` field and default bucket will be used as name and bucket respectively to create an
instance of `BlobId`

See <<configuring_converters,Configuring a Spring Converter>> for more information on how to register a converter.

=== Setting Content

Storing content is achieved using the `ContentStore.setContent(T entity, PropertyPath path, InputStream content, SetContentParams params)` method.

The `PropertyPath` will be used to resolve the content property to update.

If content has not yet been stored with this entity and an Id has not been assigned, one will be generated based in `java.util.UUID`.

The `@ContentId` and `@ContentLength` annotations will be updated on `entity`.

If content has previously been stored it will be overwritten also updating the @ContentLength attribute, if present.  However, using `ContentDisposition.Create` on the `SetContentParams` a new Id will be assigned and content stored, leaving the existing content in place and orphaned.

=== Getting Content

Content can be accessed using the `ContentStore.getContent(T entity, PropertyPath path)` method.

=== Unsetting Content

Content can be removed using the `ContentStore.unsetContent(T entity, PropertyPath path, UnsetContentParams params)` method.  Using `ContentDisposition.Keep` on `UnsetContentParams` will leave the content in storage and orphaned.

=== Configuring a Spring Converter
[[configuring_converters]]

To configure Spring Content Azure Storage with one or more Spring Converters that convert your Entities, or IDs, to an
instance of BlobId the following approach can be used:

.Configuring Spring Content Azure Storage with a custom Spring Converter
====
[source, java]
----
@Configuration
public class AzureStoreConfiguration  {

    @Bean
    public AzureStorageConfigurer configurer() {
        return new AzureStorageConfigurer() {

            @Override
            public void configureAzureStorageConverters(ConverterRegistry registry) {
                registry.addConverter(new Converter<TestEntity, BlobId>() {
                    @Override
                    public BlobId convert(TestEntity entity) {
                        return BlobId.of(entity.getCustomBucketField(), entity.getCustomContentIdField());
                    }
                });
            }
        }
    }
}
----
====
