= Filesystem Content Repositories

== Annotation based configuration

Spring Content Filesystem repositories are enabled with the following Java Config.

.Spring Content Filesystem repositories using Java Config
====
[source, java]
----
@Configuration
@EnableFilesystemContentRepositories
public static class ApplicationConfig {
}
----
====

By default content will be stored in a randomly chosen (at application startup) folder under `java.io.tmdir`.

==Configuring

The following configuration properties (prefix `spring.content.fs`) are supported.

[cols="2*", options="header"]
|=========
| Property | Description
| filesystemRoot | content store location (defaults to `java.io.tmpdir/<random>/`.  
|=========

== Accessing Content

=== Setting Content

Storing content is achieved using the `ContentRepostory.setContent(entity, InputStream)` method.  

If content has not yet been stored with this entity before and an ID has not been assigned one will be generated.  

From this ID the `PlacementService` will then be used to determine the physical storage location and the content will be stored.

The @ContentId and @ContentLength annotations will be updated on `entity`.  

If content has been previously stored it will overwritten updating just the @ContentLength attribute, if appropriate.

=== Getting Content

Content can be accessed using the `ContentRepository.getContent(entity)` method.  

=== Unsetting Content

Content can be removed using the `ContentRepository.unsetContent(entity)` method.
