= Filesystem Content Repositories

== Annotation based configuration

Spring Content Filesystem repositories are enabled with the following Java Config.

.Spring Content Filesystem repositories using Java Config
====
[source, java]
----
@Configuration
@EnableFilesystemContentRepositories
public static class ApplicationConfig {
}
----
====

By default content will be stored in a randomly chosen (at application startup) folder under `java.io.tmdir`.

== Configuring

The following configuration properties (prefix `spring.content.fs`) are supported.

[cols="2*", options="header"]
|=========
| Property | Description
| filesystemRoot | content store location (defaults to `java.io.tmpdir/<random>/`.  
|=========

== Accessing Content

=== Storage Configuration

By default Spring Content Filesystem will store all content at the root of the content store location.  

The Filesystem Store uses a dedicated `ConversionService` to convert the content entity's ID into a resource path.  By configuring your application to contribute one (or more) `org.springframework.content.fs.configFilesytemStoreConverter` it is possible to configure the Store to use other. more sophisticated storage models.  

For example Content IDs of type `java.util.UUID` or `java.net.URI` can both be mapped to a nested resource path that will have the effect of distributing content evenly over the Store.       
 
.Configuring the Filesystem Store  
====
[source, java]
----
@Configuration
public class FilesystemStoreConfiguration  {

	@Bean
	public FilesystemStoreConverter<UUID,String> uuidConverter() {
		return new FilesystemStoreConverter<UUID,String>() {
			@Override
			public String convert(UUID source) {
				return String.format("/%s", source.toString().replaceAll("-","/"));
			}
		};
	}
}
----
====   

=== Setting Content

Storing content is achieved using the `ContentRepostory.setContent(entity, InputStream)` method.  

If content has not yet been stored with this entity before and an ID has not been assigned by the application one will be generated based on `java.util.UUID`.  

The @ContentId and @ContentLength annotations will be updated on `entity`.  

If content has been previously stored it will overwritten updating just the @ContentLength attribute, if appropriate.

=== Getting Content

Content can be accessed using the `ContentRepository.getContent(entity)` method.  

=== Unsetting Content

Content can be removed using the `ContentRepository.unsetContent(entity)` method.