= Filesystem Content Stores

== Maven Central Coordinates
The maven coordinates for this Spring Content library are:
```xml
<dependency>
    <groupId>com.github.paulcwarren</groupId>
    <artifactId>spring-content-fs</artifactId>
</dependency>
```

As it is usual to use several Spring Content libraries together importing the bom is recommended:
```xml
<dependency>
    <groupId>com.github.paulcwarren</groupId>
    <artifactId>spring-content-bom</artifactId>
    <version>${spring-content-version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
```

== Annotation-based Configuration

Spring Content Filesystem Stores are enabled with the following Java Config.

.Spring Content Filesystem Stores using Java Config
====
[source, java]
----
@Configuration
@EnableFilesystemStores
public static class ApplicationConfig {

    @Bean
    File filesystemRoot() {
        try {
            return Files.createTempDirectory("").toFile();
        } catch (IOException ioe) {}
        return null;
    }

    @Bean
    FileSystemResourceLoader fileSystemResourceLoader() {
        return new FileSystemResourceLoader(filesystemRoot().getAbsolutePath());
    }
    
}
----
====

By default content will be stored in a randomly chosen (at application startup) folder 

== Spring Boot Configuration

When using `spring-content-fs-boot-starter` (or `content-fs-spring-boot-starter`) the root for all file system stores will be a randomly chosen folder (at application start-up) under `java.io.tmdir`.

The following configuration properties (prefix `spring.content.fs`) are supported.

[cols="2*", options="header"]
|=========
| Property | Description
| filesystemRoot | The root location where file system stores place their content (defaults to `java.io.tmpdir/<random>/`).  
|=========

== Accessing Storage

=== Signature Types
[[signature_types]]

Filesystem Storage supports the following signature types:

- `org.springframework.content.fs.store.FilesystemStore`
- `org.springframework.content.fs.store.FilesystemAssociativeStore`
- `org.springframework.content.fs.store.FilesystemContentStore`

The module id for the `spring.content.storage.type.default` property is `fs`.

=== Loading Spring Resources from a Store or AssociativeStore

Resources returned by Filesystem Storage are standard Spring Resources implementing the following interfaces:

- `org.springframework.core.io.Resource`
- `org.springframework.core.io.WriteableResource`
- `org.springframework.content.commons.io.DeleteableResoure`

When a Resource is loaded from the Store the following rules are used to determine the resource's location.

For a `Store`, when a Resource is loaded using a call to `getResource(ID location)`.

- if the store's ID is typed to a `String` this will be used as-is as the resource's location
- otherwise, if a registered Spring Converter exists that converts the Store's ID type to a String this will be used to 
convert the value to a String location

For an `AssociativeStore` (or indirectly a `ContentStore`), when a Resource is loaded from a call to `getResource(S entity)`:

- if a registered Spring Converter exists that converts the the Store's entity (S) type to a `String` this will be used
convert the value to a String location.
- otherwise, the Entity's `@ContentId` field will be used as the resource's location

See <<configuring_converters,Configuring a Spring Converter>> for more information on how to register a converter.

=== Setting Content

Storing content is achieved using the `ContentStore.setContent(T entity, PropertyPath path, InputStream content, SetContentParams params)` method.

The `PropertyPath` will be used to resolve the content property to update.

If content has not yet been stored with this entity and an Id has not been assigned, one will be generated based in `java.util.UUID`.

The `@ContentId` and `@ContentLength` annotations will be updated on `entity`.

If content has previously been stored it will be overwritten also updating the @ContentLength attribute, if present.  However, using `ContentDisposition.Create` on the `SetContentParams` a new Id will be assigned and content stored, leaving the existing content in place and orphaned.

=== Getting Content

Content can be accessed using the `ContentStore.getContent(T entity, PropertyPath path)` method.

=== Unsetting Content

Content can be removed using the `ContentStore.unsetContent(T entity, PropertyPath path, UnsetContentParams params)` method.  Using `ContentDisposition.Keep` on `UnsetContentParams` will leave the content in storage and orphaned.

=== Storage Customization
[[configuring_converters]]

By default, the Filesystem Store Module will store all content at the root of the backing store.  Usually, this
is sufficient.

However, for the cases where you need more control over the content in the backing store, the Module provides a placement
service.  This service can be configured through a standard Spring converter in a couple of different ways, depending
on requirements.

Assume you have a Document entity like this:

```
@Entity
@Data
public class Document {

    @Id
    @GeneratedValue(strategy=AUTO)
    private Long id;

    @ContentId
    private UUID contentId;

    @ContentLength
    private Long contentLength;

    @MimeType
    private String mimeType;

    private String contentPath;
}
```

The first option is a converter that converts from the `@ContentId` type, in this case UUID, to String.

.Spring Content Filesystem Stores customizing storage customization by `@ContentId` type
====
[source, java]
----
@Configuration
public class FilesystemStoreConfiguration  {

   	public Converter<UUID,String> converter() {
		return new FilesystemStoreConverter<UUID,String>() {

			@Override
			public String convert(UUID source) {
				return String.format("/%s", source.toString().replaceAll("-", "/"));
			}
		};
	}

	@Bean
	public FilesystemStoreConfigurer configurer() {
		return new FilesystemStoreConfigurer() {

			@Override
			public void configureFilesystemStoreConverters(ConverterRegistry registry) {
				registry.addConverter(converter());
			}
		};
	}
}
----
This example uses a converter to generate a random location on disk based on the contentId

For example, a Document with a contentId of `ec39f99b-5de3-4dc5-9753-a97c26f809c2` would be stored in the
backing store at `/ec39f99b/5de3/4dc5/9753/a97c26f809c2`.
====

The second option is a converter that converts from the Entity type to String.

.Spring Content Filesystem Stores customizing storage customization by Entity type
====
[source, java]
----
@Configuration
public static class StoreConfig {
    @Bean
    public FilesystemStoreConfigurer configurer() {
        return new FilesystemStoreConfigurer() {

            @Override
            public void configureFilesystemStoreConverters(ConverterRegistry registry) {
                registry.addConverter(new Converter<Document, String>() {

                    @Override
                    public String convert(Document document) {
                        return document.getContentPath();
                    }
                });
            }
        };
    }

	@Bean
	public FilesystemStoreConfigurer configurer() {
		return new FilesystemStoreConfigurer() {

			@Override
			public void configureFilesystemStoreConverters(ConverterRegistry registry) {
				registry.addConverter(converter());
			}
		};
	}
}
----
This example allows the application to control the location in the backing store with a field on the entity.

For example, if you created a Document and set its contentPath to `/path/to/my-file` the content will be stored in the
backing store at `/path/to/my-file`.
====
