= Filesystem Content Repositories

== Annotation based configuration

Spring Content Filesystem repositories are enabled with the following Java Config.

.Spring Content Filesystem repositories using Java Config
====
[source, java]
----
@Configuration
@EnableFilesystemContentRepositories
public static class ApplicationConfig {

	@Bean
	public File fileSystemRoot() throws IOException {  # <1>
		return Files.createTempDirectory("").toFile();
	}
	
}
----
<1> Define a bean called `fileSystemRoot` to instruct Spring Content Filesystem where the root of the content store should be
====

== Accessing Content

=== Setting Content

Storing content is achieved using the `ContentRepostory.setContent(entity, InputStream)` method.  If content has not been associated with this entity before an ID and storage location (under the content store root) will be generated, the content will be stored and the @ContentId and @ContentLength annotations will be updated on `entity`.  Otherwise it will overwrite the previously stored content updating just the @ContentLength attribute, if appropriate.

=== Getting Content

Content can be accessed using the `ContentRepository.getContent(entity)` method.  

=== Unsetting Content

Content can be removed using the `ContentRepository.unsetContent(entity)` method.
