= JPA Content Stores

== Annotation based configuration

Spring Content JPA Stores are enabled with the following Java Config.

.Spring Content JPA Stores using Java Config
====
[source, java]
----
@Configuration
@EnableJpaRepositories
@EnableJpaContentRepositories
@EnableTransactionManagement
public static class ApplicationConfig {  

  @Bean
  public DataSource dataSource() {

    EmbeddedDatabaseBuilder builder = new EmbeddedDatabaseBuilder();
    return builder.setType(EmbeddedDatabaseType.HSQL).build();
  }

  @Bean
  public LocalContainerEntityManagerFactoryBean entityManagerFactory() {

    HibernateJpaVendorAdapter vendorAdapter = new HibernateJpaVendorAdapter();
    vendorAdapter.setGenerateDdl(true);

    LocalContainerEntityManagerFactoryBean factory = new LocalContainerEntityManagerFactoryBean();
    factory.setJpaVendorAdapter(vendorAdapter);
    factory.setPackagesToScan("com.acme.domain");
    factory.setDataSource(dataSource());
    return factory;
  }

  @Bean
  public PlatformTransactionManager transactionManager() {

    JpaTransactionManager txManager = new JpaTransactionManager();
    txManager.setEntityManagerFactory(entityManagerFactory());
    return txManager;
  }
	
}
----
====

This configuration class sets up an embedded HSQL database using the EmbeddedDatabaseBuilder API from spring-jdbc.  We then set up an EntityManagerFactory and use Hibernate as the persistence provider.  The last infrastructure component declared here is the JpaTransactionManager.  

We activate Spring Data JPA repositories using the @EnableJpaRepositories annotation,  Spring Content JPA stores using @EnableJpaContentRepositories and enable transaction management with the @EnableTransactionManagement annotation.

If no base packages are configured both Spring Data JPA and Spring Content JPA will use the one the configuration class resides in.

== Persisting Content

=== Setting Content

Storing content is achieved using the `ContentStore.setContent(entity, InputStream)` method.  

The Spring Content Commons provided `PlacementService` is used to determine the actual physical storage location by parsing the @ContentId field into a resource path.

The `entity` @ContentId and @ContentLength fields will be updated.  

If content has been previously stored this will overwritten with the new content updating just the @ContentLength field, if appropriate.

==== How the @ContentId field is handled 

Spring Data JPA requires that content entities have an `@ContentId` field for identity that will be generated when content is initially set.  

=== Getting Content

Content can be accessed using the `ContentStore.getContent(entity)` method.  

=== Unsetting Content

Content can be removed using the `ContentStore.unsetContent(entity)` method.
