= JPA Content Stores

== Annotation based configuration

Spring Content JPA Stores are enabled with the following Java Config.

.Spring Content JPA Stores using Java Config
====
[source, java]
----
@Configuration
@EnableJpaRepositories
@EnableJpaStores
@EnableTransactionManagement
public static class ApplicationConfig {  

  @Bean
  public DataSource dataSource() {

    EmbeddedDatabaseBuilder builder = new EmbeddedDatabaseBuilder();
    return builder.setType(EmbeddedDatabaseType.HSQL).build();
  }

  @Bean
  public LocalContainerEntityManagerFactoryBean entityManagerFactory() {

    HibernateJpaVendorAdapter vendorAdapter = new HibernateJpaVendorAdapter();
    vendorAdapter.setGenerateDdl(true);

    LocalContainerEntityManagerFactoryBean factory = new LocalContainerEntityManagerFactoryBean();
    factory.setJpaVendorAdapter(vendorAdapter);
    factory.setPackagesToScan("com.acme.domain");
    factory.setDataSource(dataSource());
    return factory;
  }

  @Bean
  public PlatformTransactionManager transactionManager() {

    JpaTransactionManager txManager = new JpaTransactionManager();
    txManager.setEntityManagerFactory(entityManagerFactory());
    return txManager;
  }
	
}
----
====

This configuration class sets up an embedded HSQL database using the EmbeddedDatabaseBuilder API from spring-jdbc.  We
then set up an EntityManagerFactory and use Hibernate as the persistence provider.  The last infrastructure component
declared here is the JpaTransactionManager.

We activate Spring Data JPA repositories using the `@EnableJpaRepositories` annotation.  We activate Spring Content JPA
stores using `@EnableJpaStores` and enable transaction management with the `@EnableTransactionManagement` annotation.

If no base packages are configured both Spring Data JPA and Spring Content JPA will use the package that the
configuration class resides in as the base package.

=== Content Streaming

Spring Content JPA attempts to provide streams that chunk BLOBs through the memory space of the JVM rather that loading
the entire BLOB into memory.  In order to do this the following database-specific implementation are used.

==== MySQL

The MySQL implementation requires MySQL's locator emulation to be turned on.  Your JDBC connection string must
include the `emulateLocators=true` parameter.

=== Postgresql

The Postgresql implementation uses the OID field type and the Large Object API.  Whilst this provides properly chuncked
streams it does comes with a significant performance disadvantage over bytea fields.

=== SQL Server

The SQL Server implementation uses [adaptive buffering](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-adaptive-buffering?view=sql-server-2017#setting-adaptive-buffering)
to serve BLOBs in a memory efficient way.

== Persisting Content

=== Setting Content

Storing content is achieved using the `ContentStore.setContent(entity, InputStream)` method.  

The entity's `@ContentId` and `@ContentLength` fields will be updated.

If content has been previously stored this will overwritten with the new content updating just the `@ContentLength`
field, if appropriate.

==== How the @ContentId field is handled 

Spring Data JPA requires that content entities have an `@ContentId` field for identity that will be generated when
content is initially set.

=== Getting Content

Content can be accessed using the `ContentStore.getContent(entity)` method.  

=== Unsetting Content

Content can be removed using the `ContentStore.unsetContent(entity)` method.

