= JPA Content Stores

== Maven Central Coordinates
The maven coordinates for this Spring Content library are as follows:
```xml
<dependency>
    <groupId>com.github.paulcwarren</groupId>
    <artifactId>spring-content-jpa</artifactId>
</dependency>
```

As it is usual to use several Spring Content libraries together importing the bom is recommended:
```xml
<dependency>
    <groupId>com.github.paulcwarren</groupId>
    <artifactId>spring-content-bom</artifactId>
    <version>${spring-content-version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
```

== Annotation based configuration

Spring Content JPA Stores are enabled with the following Java Config.

.Spring Content JPA Stores using Java Config
====
[source, java]
----
@Configuration
@EnableJpaRepositories
@EnableJpaStores
@EnableTransactionManagement
public static class ApplicationConfig {  

  @Bean
  public DataSource dataSource() {
    EmbeddedDatabaseBuilder builder = new EmbeddedDatabaseBuilder();
    return builder.setType(EmbeddedDatabaseType.HSQL).build();
  }

  @Bean
  public LocalContainerEntityManagerFactoryBean entityManagerFactory() {
    HibernateJpaVendorAdapter vendorAdapter = new HibernateJpaVendorAdapter();
    vendorAdapter.setGenerateDdl(true);

    LocalContainerEntityManagerFactoryBean factory = new LocalContainerEntityManagerFactoryBean();
    factory.setJpaVendorAdapter(vendorAdapter);
    factory.setPackagesToScan("com.acme.domain");
    factory.setDataSource(dataSource());
    return factory;
  }

  @Bean
  public PlatformTransactionManager transactionManager() {
    JpaTransactionManager txManager = new JpaTransactionManager();
    txManager.setEntityManagerFactory(entityManagerFactory());
    return txManager;
  }

  @Value("/org/springframework/content/jpa/schema-drop-hsqldb.sql")
  private Resource dropRepositoryTables;

  @Value("/org/springframework/content/jpa/schema-hsqldb.sql")
  private Resource createRepositoryTables;

  @Bean
  DataSourceInitializer datasourceInitializer() {
    ResourceDatabasePopulator databasePopulator = new ResourceDatabasePopulator();

    databasePopulator.addScript(dropRepositoryTables);
    databasePopulator.addScript(createRepositoryTables);
    databasePopulator.setIgnoreFailedDrops(true);

    DataSourceInitializer initializer = new DataSourceInitializer();
    initializer.setDataSource(dataSource());
    initializer.setDatabasePopulator(databasePopulator);

    return initializer;
  }
}
----
====

This configuration class sets up an embedded HSQL database.  The first three beans are standard for any spring JPA application; `dataSource`, `entityManageFactory` and `transactionManager`.

The last bean prepares the database to be able to store content by creating database schema.  Replace the `dropRepositoryTables` and `createRepositoryTables` resources with the appropriate ones for your database (`h2`, `hsqldb`, `mysql`, `oracle`, `postgresql`, `sqlserver`).  Creating this bean manually is only requires when using `spring-content-jpa` directly.  The spring-content-jpa boot starter will create this bean if not present.

We activate Spring Data JPA repositories using the `@EnableJpaRepositories` annotation.  We activate Spring Content JPA
stores using `@EnableJpaStores` (also only required when not using the boot starter) and enable transaction management with the `@EnableTransactionManagement` annotation.

== Accessing Content

=== Signature Types
[[signature_types]]

JPA Storage supports the following signature types:

- `org.springframework.content.jpa.store.JpaContentStore`

The module id for the `spring.content.storage.type.default` property is `jpa`.

=== Content Streaming

Spring Content JPA attempts to provide streams that chunk BLOBs through the memory space of the JVM rather that loading
the entire BLOB into memory.  In order to do this the following database-specific implementation are used.

==== MySQL

Despite the JDBC API that returns ``InputStream``'s for streaming BLOBs.  By default the MySQL JConnector JDBC Driver
will load the entire BLOB into the memory-space of the JVM running the JDBC client.  This risks ``OutOfMemoryException``'s
being thrown, the likelihood of which increase as the size of the BLOBs being stored increase.

However, a feature called "locator emulation" switches the implementation that is used for the getBlob() JDBC API to one
that actually does stream the content properly (i.e. in reasonable size chunks) through the memory-space of the JVM.

Spring Content JPA is designed to be used with this feature and therefore you must add the property
`emulateLocators=true` to your https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-implementation-notes.html[JDBC Connection string URL]

=== Postgresql

The Postgresql implementation uses the OID field type and the Large Object API.  Whilst this provides properly chuncked
streams it does come with a significant performance disadvantage over bytea fields.

Large Objects *must* be accessed within a transaction.  Therefore, Store API access must also be within a transaction.  For
convenience `ContentStore` modification methods are already marked as `@Transactional`.  Note, however query methods are not and
therefore the transaction must be handled by the consumer.

=== SQL Server

The SQL Server implementation uses https://docs.microsoft.com/en-us/sql/connect/jdbc/using-adaptive-buffering?view=sql-server-2017#setting-adaptive-buffering[adaptive buffering]
to serve BLOBs in a memory efficient way.

=== Oracle

The oracle implementation relies on the ability of the Oracle JDBC driver to perform chunked operations on the
streams. This functionality has been tested against the com.oracle.database.jdbc ojdbc instance at version 12.2.0.1,
where the default prefetch size is 4000 bytes. Whilst the driver supports the ability to modify this prefetch size
for tuning performance, there currently is no way to over-ride this setting via the spring-content API, so the default
of whatever driver version is in use will apply.

== Persisting Content

=== Setting Content

Storing content is achieved using the `ContentStore.setContent(entity, InputStream)` method.  

The entity's `@ContentId` and `@ContentLength` fields will be updated.

If content has been previously stored this will overwritten with the new content updating just the `@ContentLength`
field, if appropriate.

==== How the @ContentId field is handled 

Spring Data JPA requires that content entities have an `@ContentId` field for identity that will be generated when
content is initially set.

=== Getting Content

Content can be accessed using the `ContentStore.getContent(entity)` method.  

=== Unsetting Content

Content can be removed using the `ContentStore.unsetContent(entity)` method.
