[[fulltext-search]]
= Fulltext Indexing & Searching with Solr

== Overview

When enabled, the Solr integration will forward all content to an Solr cluster for fulltext indexing.

== Dependencies

Spring Content Solr requires a `SolrClient` bean that is used as the connection to the Solr
cluster that you wish to use for indexing.

Solr is therefore enabled with following depedencies:

====
[source, xml]
----
	<dependency>
		<groupId>org.apache.solr</groupId>
		<artifactId>solr-solrj</artifactId>
		<version>7.2.1</version>                <1>
		<exclusions>
			<exclusion>
				<groupId>org.codehaus.woodstox</groupId>
				<artifactId>wstx-asl</artifactId>
			</exclusion>
			<exclusion>
				<artifactId>log4j</artifactId>
				<groupId>log4j</groupId>
			</exclusion>
		</exclusions>
	</dependency>
----
1. Specify the version that matches your Solr server.  NB: as Spring Content certifies against the latest version, the
version must be compatible with this.
====

And the following Java Config:

.Enabling Spring Content Solr with Java Config
====
[source, java]
----
@Configuration
@EnableFullTextSolrIndexing                 <1>
@EnableFilesystemStores                     <2>
public static class ApplicationConfig {

    @Bean                                   <3>
    public SolrClient solrClient() {
        return new HttpSolrClient.Builder("http://localhost:8983/solr/solr").build();
    }

}
----
1. Specify the `@EnableFullTextSolrIndexing` annotation in an `@Configuration` class
2. Spring Content Solr works with any Spring Content Store Module
3. Ensure a `(SolrJ) SolrClient` `@Bean` is instantiated somewhere within your `@Configuration`
====

== Configuring

If required, credentials can be specified using the following configuration properties.

[cols="2*", options="header"]
|=========
| Property | Description
| solr.username | Solr user
| solr.password | Solr user's password
|=========

== Making Stores Searchable

With fulltext-indexing enabled, Store interfaces can be made `Searchable`.  See
<<content-repositories.search,Searchable Stores>> for more information on how to do this.

== Custom Indexing

When you `@EnableFullTextSolrIndexing` a store event handler is registered that intercepts content being added to a
Store and sends that content to your Solr instance for full-text indexing.  This is usually all you need.  However,
sometimes you may need more control over when documents are indexed.  For these cases you can use the `IndexService`
bean directly in your code to index (or unindex) content as required.