[[solr-search]]
= Indexing & Searching with Solr

== Overview

When enabled the Solr integration will forward all content to Solr for fulltext indexing which can then be searched by adding the optional `Searchable<CID>` interface to the Content Repositories.

== Dependencies

Add the solrj to the classpath.

====
[source, java]
----
	<dependency>
		<groupId>org.apache.solr</groupId>
		<artifactId>solr-solrj</artifactId>
		<version>5.5.3</version>			<1>
		<exclusions>
			<exclusion>
				<groupId>org.codehaus.woodstox</groupId>
				<artifactId>wstx-asl</artifactId>
			</exclusion>
			<exclusion>
				<artifactId>log4j</artifactId>
				<groupId>log4j</groupId>
			</exclusion>
		</exclusions>
	</dependency>
----
<1> If using Spring Boot the version may be omitted
====

== Enabling

- Specify the `@EnableFullTextSolrIndexing` annotation to your `@Configuration` Spring Application block.
- Ensure a `(SolrJ) SolrClient` `@Bean` is instantiated somewhere within your `@Configuration` Spring Application block.

== Configuring

By default when the Solr module is enabled Spring-Content looks for a `http://localhost:8983/solr/solr` solr server with no username or password.

To change this behavior the following variables need to be set via the https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config[Externalized Configuration] method.

[cols="2*", options="header"]
|=========
| Property | Description
| solr.url | Url of the Solr host (including port and core)
| solr.username | Solr user
| solr.password | Solr user's password
|=========
