= Introduction

REST web services have become the number one means for application integration on the web. In its core, REST defines that a system consists of resources that clients interact with. These resources are often also implemented in a hypermedia driven way.  Spring MVC offers a solid foundation to build theses kinds of services.  But implementing even the simplest REST web services for a multi-domain object system can be quite tedious and result in a lot of boilerplate code.

Spring Content REST builds on top of Spring Content stores and automatically exports those as REST resources.  It leverages REST to expose end-points for each content resource and it also optionally integrates with Spring Data REST's hypermedia API to allow clients to find content resources that have been associated with Spring Data entities.

Spring Content REST officially supports:

- https://github.com/paulcwarren/spring-content/spring-content-fs[Spring Content Filesystem]
- https://github.com/paulcwarren/spring-content/spring-content-s3[Spring Content S3]
- https://github.com/paulcwarren/spring-content/spring-content-mongo[Spring Content Mongo]
- https://github.com/paulcwarren/spring-content/spring-content-jpa[Spring Content JPA]

= Getting Started

== Introduction

Spring Content REST is itself a Spring MVC application and is designed in such a way that it should integrate with your existing Spring MVC applications with very little effort. 

== Adding Spring Content REST to a Spring Boot project

The simplest way to get to started is if you are building a Spring Boot application. That’s because Spring Content REST has both a starter as well as auto-configuration.

.Spring Boot configuration with Gradle
====
[source, java]
----
dependencies {
    ...
    compile("com.github.paulcwarren:spring-content-rest-boot-starter:${version}")
	... 
}
----
====

.Spring Boot configuration with Maven
====
[source, java]
----
 <dependencies>
	...
    <dependency>
      <groupId>com.github.paulcwarren</groupId>
      <artifactId>spring-content-rest-boot-starter</artifactId>
      <version>${version}</version>
    </dependency>
	...
  </dependencies>
----
====

When using Spring Boot, Spring Content REST gets configured automatically.

== Adding Spring Content REST to a Gradle Project

To add Spring Content REST to a Gradle-based project, add the spring-content-rest artifact to your compile-time dependencies:

====
[source, java]
----
dependencies {
    ...
    compile("com.github.paulcwarren:spring-content-rest:${version}")
	... 
}
----
====

== Adding Spring Content REST to a Maven Project

To add Spring Content REST to a Maven-based project, add the spring-content-rest artifact to your compile-time dependencies:
====
[source, java]
----
 <dependencies>
	...
    <dependency>
      <groupId>com.github.paulcwarren</groupId>
      <artifactId>spring-content-rest</artifactId>
      <version>${version}</version>
    </dependency>
	...
  </dependencies>
----
====

== Configuring Spring Content REST

To install Spring Content REST alongside your existing Spring MVC application, you need to include the appropriate MVC configuration.  Spring Content REST configuration is defined in two classes  called; `RestConfiguration` and `HypermediaConfiguration` and they can just be imported into your applications configuration.

IMPORTANT: This step is unnecessary if you are using Spring Boot’s auto-configuration. Spring Boot will automatically enable Spring Content REST when you include `com.github.paulcwarren:spring-content-rest-boot-starter` and your app is flagged as a `@SpringBootApplication`.

Make sure you also configure Spring Content stores for the store you wish to use.  For details on that, please consult the reference documentation for the corresponding Spring Content module.

= Store Resources

== Fundamentals

The core functionality of Spring Content REST, enabled through `@Import(RestConfiguration.class)`, is to export resources
for Spring Content stores.  This is often closely related to Spring Data repositories.

The following describes typical store scenarios and how they are exported with Spring Content REST.

=== Resources

Spring Content Stores manage Spring Resources that, when exported using Spring Content REST, are accessible by REST
endpoint.

Consider the following Store interface:

====
[source, java]
----
  public interface DvdStore extends Store<String> {}
----
====

In this example, the Store's Resources are exported to the URI `/dvds`.  The path is derived from the
uncapitalized, pluralized, simple class name of the interface.  When interacting with this endpoint any additional path
is deemed to be the Resource's location and will be used to fetch the Resource using the Store's `getResource` method.
For example, a GET request to `/dvds/comedy/monty_pythons_flying_circus.mp4` will fetch from the `DvdStore` (`/dvds`),
the Resource `/comedy/monty_pythons_flying_circus.mp4`.

=== Entity Resources

Entity Resources are Spring Resource associated with Spring Data Entities.

Assume the following `Entity` class, `Repository` and `Store` interfaces:
  
====
[source, java]
----
  @Entity
  public class Dvd {
  	@Id
  	private Long id;

    @ContentId
    private UUID contentId;

  	@ContentLength
  	private Long contentLength;
  	
  	@MimeType
  	private String mimeType;
  	
  	// getters and setters
  }
  
  public interface DvdRepository extends CrudRepository<Dvd, Long> {}

  public interface DvdStore extends ContentStore<Dvd, UUID> {}
----
====
  
In this example a single Spring Resource (the DVD's video stream) is associated with a Dvd Entity by annotating additional
fields on the Entity using the `@ContentId`, `@ContentLength` and `@MimeType` annotations.   In this example Spring Data
REST exports a collection  resource to `/dvds`.  The path is derived from the uncapitalized, pluralized, simple class
name of the domain class.  Item resources are also exported to the URI `/dvds/{id}`.  The HTTP methods used to request
this endpoint map onto the methods of `CrudRepository`.

Similarly, Spring Content REST also exports any associated Spring Resources to the URI `/dvds/{id}`.  In this case the
HTTP methods map onto the methods of `ContentStore` as follows:-

- GET -> getContent
- POST/PUT -> setContent
- DELETE -> unsetContent

=== Property Resources

Property Resources are associated with the properties of Spring Data Entities, that themselves maybe Spring Data Entities.
This allows many Resources to be associated with a single Entity.

Consider the following `Entity` model, with `Repository` and `Store` interfaces:

====
[source, java]
----
@Entity
public class Dvd {
	private @Id @GeneratedValue Long id;
	private String title;

	@OneToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "image_id")
	private Image image;
	
	@OneToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "stream_id")
	private Stream stream;
	
	...
}

@Entity
public class Image {
	// Spring Data managed attribute
	private @Id @GeneratedValue Long id;

	@OneToOne
	private Dvd dvd;

	// Spring Content managed attributes
	private @ContentId UUID contentId;  	
	private @ContentLength Long contentLen;	
}

@Entity
public class Stream {
	// Spring Data managed attribute
	private @Id @GeneratedValue Long id;

	@OneToOne
	private Dvd dvd;

	// Spring Content managed attributes
	private @ContentId UUID contentId;  	
	private @ContentLength Long contentLen;	
}

public interface DvdRepository extends CrudRepository<Dvd, Long> {}

public interface ImageStore extends ContentStore<Image, UUID> {}

public interface StreamStore extends ContentStore<Stream, UUID> {}
----
====  

In this example separate Resources are associated with the `image` and `stream` properties of the `Dvd` Entity.

When using JPA and its relational characteristics these associations are typically (but not always) also Entity
associations as well, as shown here.  However when using NoSQL databases like MongoDB that are capable of storing
hierarchical data they are true property associations.

As before, Spring Data REST will export an item resource under the URI `/dvds/{id}`.  However, this time Spring Content
REST will export Property Resources to the URI `/dvds/{id}/image/{contentId}` and `/dvds/{id}/stream/{contentId}`
managed by the respective Store.  A property can be set by POSTing to `/dvds/{id}/image` (or `/dvds/{id}/stream`).

NOTE: as these properties are both single values these Resources are also available under the simplified URI
`/dvds/{id}/image` and `/dvds/{id}/stream` where the `{contentId}` is omitted for convenience.

=== Property Collection Resources

Property Resources can also target Collections.

Consider the following example:-

====
[source, java]
----
@Entity
public class Dvd {
	private @Id @GeneratedValue Long id;
	private String title;

	@OneToMany
	@JoinColumn(name = "chapter_id")
	private List<Chapter> chapters;

	...
}

@Entity
public class Chapter {
	// Spring Data managed attribute
	private @Id @GeneratedValue Long id;

	// Spring Content managed attributes
	private @ContentId UUID contentId;  	
	private @ContentLength Long contentLen;	
}

public interface DvdRepository extends CrudRepository<Dvd, Long> {}

public interface ChapterStore extends ContentStore<Chapter, UUID> {}
----
====

In this example many Resources can be associated with the `chapters` property of the `Dvd` Entity.

As with Property Resources, Property Collection Resources are also exported to the URI `/dvds/{id}/chapters`.
However, in this case, POSTing to `/dvds/{id}/chapters` always *appends* a new Resource to the 'Chapters' Collection.
This Resource supports both POST and PUT HTTP methods.

=== Search

Exported content stores may be marked as `Searchable`.  Assume the following content store interface:

====
[source, java]
----
  public interface DvdStore extends ContentStore<Dvd, UUID>, Searchable<UUID> {}
----
====

When exported Spring Content REST exposes a fulltext query resource for each `Searchable` method.  These resources are
 exported under the URI `/dvds/searchContent/<findMethod>`.  Method parameters are supplied as query parameters:

====
[source, sh]
----
  curl http://localhost:8080/dvds/searchContent/findKeywords?keyword=one&keyword=two
----
====

=== Default status codes

For the content resources exposed, we use a set of default status codes:

- 200 OK - for plain GET requests and POST and PUT requests that overwrite existing content resources
- 201 Created - for POST and PUT requests that create new content resources
- 204 No Content - for DELETE requests 
- 206 Partial Content - for range GET requests

=== Resource Discoverability

A core principle of HATEOAS is that Resources should be discoverable through the publication of links that point to the
available resources.  There are a few competing de-facto standards specifying how to represent links in JSON.  By default,
Spring Data REST uses HAL to render responses.  HAL defines links to be contained in a property of the returned document.

Resource discovery starts at the top level of the application.  By issuing a request to the root URL under which the
Spring Data REST application is deployed, the client can extract a set of links from the returned JSON object that
represent the next level of resources that are available to the client.

When enabled through `@Import(HypermediaConfiguration.class)` Spring Content REST will inject Store, Entity and Property
Resources links for both into the HAL responses created by Spring Data REST.

== The Store Resource

Spring Content REST exports Store Resources to `/{store}/**`.  The resource path and linkrel can be customized using the
`@StoreRestResource` annotation on the Store interface.

=== Supported HTTP Methods

Store Resources support `GET`, `PUT`, `POST`, and `DELETE`.  All other HTTP methods will cause a `405 Method Not
Allowed`.

==== GET

Returns the Resource's content

===== Supported media types

All content types except `application/json`

==== PUT/POST

Sets the Resources's content

===== Supported media types

All content types except `application/json`

==== DELETE

Removes the Resource's content

===== Supported media types

All content types except `application/json`

== The Entity Resource

Spring Content REST exports Entity Resources to `/{store}/{id}`.  The resource path can be customized using the
`@StoreRestResource` annotation on the Store interface.
 
=== Supported HTTP Methods

Entity Resources support `GET`, `PUT`, `POST`, and `DELETE`.  All other HTTP methods will cause a `405 Method Not
Allowed`.

==== GET

Returns the Resource's content 

===== Supported media types

All content types except `application/json`

==== PUT/POST

Sets the Resources's content

===== Supported media types

All content types except `application/json`
 
==== DELETE

Removes the Resource's content

===== Supported media types

All content types except `application/json`

== The Property Resource

Spring Content REST exports Property Resources to `/{store}/{id}/{property}` and `/{store}/{id}/{property}/{contentId}`.
The resource path can be customized using the `@StoreRestResource` annotation on the Store interface.

=== Supported HTTP Methods

Property Resources support `GET`, `PUT`, `POST`, and `DELETE`.  All other HTTP methods will cause a `405 Method Not
Allowed`.

==== GET

Returns the Resource's content

===== Supported media types

All content types except `application/json`

==== PUT/POST

Sets the Resources's content

===== Supported media types

All content types except `application/json`

==== DELETE

Removes the Resource's content

== The Collection Property Resource

Spring Content REST exports Property Collection Resources to `/{store}/{id}/{property}`.  The resource path can be
customized using the `@StoreRestResource` annotation on the Store interface.
 
=== Supported HTTP Methods

Content collection resources support `PUT` and `POST`.

==== PUT/POST

Appends new content to the collection of Resources

===== Supported media types

All content types except `application/json`
