= Customizing Store Resources

== Configuring CORS

For security reasons, browsers prohibit AJAX calls to resources residing outside the current origin.  When working with
client-side HTTP requests issued by a browser you may want to enable specific HTTP resources to be accessible.

Spring Data Content supports Cross-Origin Resource Sharing (CORS) through Spring’s CORS support.

=== Store interface CORS configuration

You can add a @CrossOrigin annotation to your store interfaces to enable CORS for the whole store.  By default
@CrossOrigin allows all origins and HTTP methods:

====
[source, java]
----
@CrossOrigin
interface DvdStore extends ContentStore<Dvd, UUID> {}
----
====

In the above example CORS support is enabled for the whole DvdStore.  @CrossOrigin also provides attributes to perform
more granular configuration.

====
[source,java]
----
@CrossOrigin(origins = "http://mydomain.com",
  methods = { RequestMethod.GET, RequestMethod.POST, RequestMethod.DELETE },
  maxAge = 3600)
interface DvdStore extends ContentStore<Dvd, UUID> {}
----
====

This example enables CORS support for the whole DvdStore providing one origin, restricted to GET, POST and DELETE
methods with a max age of 3600 seconds.

