== Put/Post Content Handling

A `ContentStore` provides two methods for setting content.  Spring Content REST prefers to use 
`setContent(S entity, InputStream)` over `setContent(S entity, Resource)` so that content is streamed through 
the application.  This is usually the best approach.

However, under some circumstances this can be inconvenient when event handlers and store customizations 
must handle the content as it moves through the application.  This also becomes inefficient when the
content is large and the content needs to be processed several times.

For these situations, it is possible to configure Spring Content REST to call `setContent(S entity, Resource)` as 
follows:

.Configuring PUT/POST Handling
====
[source, java]
----
public interface ExampleStore extends ContentStore<Example, UUID>{}

@Configuration
public static class ApplicationConfig {

   @Bean
   public ContentRestConfigurer configurer() {
       return new ContentRestConfigurer() {
           @Override
           public void configure(RestConfiguration config) {
               config.forDomainType(Example.class).putAndPostPreferResource();
           }
       };
   }
}
----
====

NOTE: if preferred, it is also possible to configure your `ContentStore` to hide the `setContent(S entity, InputStream)`
method by annotating this method with the `RestResource(export=false)` annotation.

When configured this way, Spring Content REST will create a file backed Resource allowing event handlers and store
customizations to use `File`, `RandomAccessFile` and `Channel` Java io/nio APIs to process the content stream.

If you would like to defer until runtime so that a decision can be based on the request, you can instead provide 
a `Resource<Method, HttpHeaders>`, as follows:

.Deferring PUT/POST Handling until runtime
====
[source, java]
----
public interface ExampleStore extends ContentStore<Example, UUID>{}

@Configuration
public static class ApplicationConfig {

   @Bean
   public ContentRestConfigurer configurer() {
       return new ContentRestConfigurer() {
           @Override
           public void configure(RestConfiguration config) {
           
               config.forDomainType(TestEntity.class).setSetContentResolver(new Resolver<Method, HttpHeaders>(){

                @Override
                public boolean resolve(Method method, HttpHeaders context) {
                    
                    return // your logic here
               }});
           }
       };
   }
}
----
====
