= Introduction

REST web services have become the number one means for application integration on the web. In its core, REST defines that a system consists of resources that clients interact with. These resources are often also implemented in a hypermedia driven way.  Spring MVC offers a solid foundation to build theses kinds of services.  But implementing even the simplest REST web services for a multi-domain object system can be quite tedious and result in a lot of boilerplate code.

Spring Content REST builds on top of Spring Content stores and automatically exports those as REST resources.  It leverages REST to expose end-points for each content resource and it also optionally integrates with Spring Data REST's hypermedia API to allow clients to find content resources that have been associated with Spring Data entities.

Spring Content REST officially supports:

- https://github.com/paulcwarren/spring-content/spring-content-fs[Spring Content Filesystem]
- https://github.com/paulcwarren/spring-content/spring-content-s3[Spring Content S3]
- https://github.com/paulcwarren/spring-content/spring-content-mongo[Spring Content Mongo]
- https://github.com/paulcwarren/spring-content/spring-content-jpa[Spring Content JPA]
- https://github.com/paulcwarren/spring-content/spring-content-gcs[Spring Content GCS]
- https://github.com/paulcwarren/spring-content/spring-content-azure-storage[Spring Content Azure Storage]

= Getting Started

== Introduction

Spring Content REST is itself a Spring MVC application and is designed in such a way that it should integrate with your existing Spring MVC applications with very little effort.

== Maven Central Coordinates
The maven coordinates for this Spring Content library are as follows:
```xml
<dependency>
    <groupId>com.github.paulcwarren</groupId>
    <artifactId>spring-content-rest</artifactId>
</dependency>
```

As it is usual to use several Spring Content libraries together importing the bom is recommended:
```xml
<dependency>
    <groupId>com.github.paulcwarren</groupId>
    <artifactId>spring-content-bom</artifactId>
    <version>${spring-content-version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
```

== Adding Spring Content REST to a Spring Boot project

The simplest way to get to started is if you are building a Spring Boot application. That’s because Spring Content REST has both a starter as well as auto-configuration.

.Spring Boot configuration with Gradle
====
[source, java]
----
dependencies {
    ...
    compile("com.github.paulcwarren:spring-content-rest-boot-starter:${version}")
	... 
}
----
====

.Spring Boot configuration with Maven
====
[source, java]
----
 <dependencies>
	...
    <dependency>
      <groupId>com.github.paulcwarren</groupId>
      <artifactId>spring-content-rest-boot-starter</artifactId>
      <version>${version}</version>
    </dependency>
	...
  </dependencies>
----
====

When using Spring Boot, Spring Content REST gets configured automatically.

== Adding Spring Content REST to a Gradle Project

To add Spring Content REST to a Gradle-based project, add the spring-content-rest artifact to your compile-time dependencies:

====
[source, java]
----
dependencies {
    ...
    compile("com.github.paulcwarren:spring-content-rest:${version}")
	... 
}
----
====

== Adding Spring Content REST to a Maven Project

To add Spring Content REST to a Maven-based project, add the spring-content-rest artifact to your compile-time dependencies:
====
[source, java]
----
 <dependencies>
	...
    <dependency>
      <groupId>com.github.paulcwarren</groupId>
      <artifactId>spring-content-rest</artifactId>
      <version>${version}</version>
    </dependency>
	...
  </dependencies>
----
====

== Configuring Spring Content REST

To install Spring Content REST alongside your existing Spring MVC application, you need to include the appropriate MVC configuration.  Spring Content REST configuration is defined in two classes  called; `RestConfiguration` and `HypermediaConfiguration` and they can just be imported into your applications configuration.

IMPORTANT: This step is unnecessary if you are using Spring Boot’s auto-configuration. Spring Boot will automatically enable Spring Content REST when you include `com.github.paulcwarren:spring-content-rest-boot-starter` and your app is flagged as a `@SpringBootApplication`.

Make sure you also configure Spring Content stores for the store you wish to use.  For details on that, please consult the reference documentation for the corresponding Spring Content module.

= Store Resources

== Fundamentals

The core functionality of Spring Content REST, enabled through `@Import(RestConfiguration.class)`, is to export resources
for Spring Content stores.  This is often closely related to Spring Data repositories.

The following describes typical store scenarios and how they are exported with Spring Content REST.

=== Store Resources

Spring Content `Store` manages Spring Resources that, when exported using Spring Content REST, are accessible by REST
endpoint.

Consider the following Store interface:

====
[source, java]
----
  public interface DvdStore extends Store<String> {}
----
====

In this example, the Store's Resources are exported to the URI `/dvds`.  The path is derived from the
uncapitalized, pluralized, simple class name of the interface.  When interacting with this endpoint any additional path
is deemed to be the Resource's location and will be used to fetch the Resource using the Store's `getResource` method.
For example, a GET request to `/dvds/comedy/monty_pythons_flying_circus.mp4` will fetch from the `DvdStore` (`/dvds`),
the Resource `/comedy/monty_pythons_flying_circus.mp4`.

=== AssociativeStore/ContentStore Resources

`AssociativeStore` and `ContentStore` both manage and associate Spring Resources with Spring Data Entities.  When exported using Spring Content REST these can also be accessed via REST endpoints.

Assume the following `Entity` class, `Repository` and `Store` interfaces:
  
====
[source, java]
----
  @Entity
  @Data
  public class Dvd {
  	@Id
  	private Long id;

    @ContentId
    private UUID contentId;

  	@ContentLength
  	private Long contentLength;
  	
  	@MimeType
  	private String contentType;
    
    @OiginalFileName
    private String contentName;
  }
  
  public interface DvdRepository extends CrudRepository<Dvd, Long> {}

  public interface DvdStore extends ContentStore<Dvd, UUID> {}
----
====
  
In this example a single Spring Resource (the DVD's video stream) is associated with a Dvd Entity by annotating additional
fields on the Entity using the `@ContentId`, `@ContentLength` and `@MimeType` annotations.   

In this example Spring Data REST exports a collection  resource to `/dvds`.  The path is derived from the uncapitalized, pluralized, simple class name of the domain class.  Item resources are also exported to the URI `/dvds {id}`.  The HTTP methods used to request this endpoint map onto the methods of `CrudRepository`.

Similarly, Spring Content REST also exports any associated Spring Resources to the URI `/dvds/{id}/{contentPropertyPath}`.  In this case `/dvds/{id}/content` because the Spring Content metadata is correlated using the prefix `content`. 

For an `AssociativeStore` the HTTP methods are mapped as follows:-
- GET -> getResource -> getInputStream
- POST/PUT -> getResource -> getOutputStream, associate 
- DELETE -> unassociate

For a `ContentStore` the HTTP methods are mapped as follows:-
- GET -> getContent
- POST/PUT -> setContent
- DELETE -> unsetContent

==== Additional Annotations

Spring Content REST adds two annotations to the core set of 
annotations provided by Spring Content Commons for capturing, 
on the entity, information that is available from the HTTP requests
made by clients. 

- `@MimeType`; captures the `Content-Type` header of POST/PUT requests
and is re-used on subsequent GET request responses

- `@OriginalFileName`; captures the filename sent by POST/PUT requests, 
if available, and is re-used to set the content dispostion attachment filename 
on subsequent GET requests 

=== Multiple Content Properties

By correlating (i.e. using a common prefix for) the field names of the Spring Content annotations it is possible to associate multiple Spring Resources with a single Entity:-

====
[source, java]
----
@Entity
@Data
public class Dvd {
	private @Id @GeneratedValue Long id;
	private String title;

	// Content property 'video' storing the DVD video content
	private @ContentId UUID videoId;  	
	private @ContentLength Long videoLen;	
	private @MimeType String videoType;

	// Content property 'image' storing the Dvd's image
	private @ContentId UUID imageId;  	
	private @ContentLength Long imageLen;	
	private @MimeType String imageType;
	
	...
}
----
====  

Spring Content REST will export these two associated Spring Resources to the URI `/dvds/{id}/video` and `/dvds/{id}/image`.

These endpoints can be found in the similarly named link relations in the Entity's
`application/hal+json` response:

====
[source, java]
----
 "_links" : {
    ...
    "image" : {
      "href" : "http://localhost:8080/dvds/1/image"
    },
    "video" : {
      "href" : "http://localhost:8080/dvds/1/video"
    }
}
----
====  

=== Nested Content Properties

With its `@Embeddable`/`@Embedded` annotations JPA along with some of the newer database technologies like Mongo it is possible to model Entities as complex objects.  It may be appropriate to associate Spring Resources as nested properties on these complex objects, as in the following example:-

====
[source, java]
----
@Entity
@Data
public class Book {
	private @Id @GeneratedValue Long id;
	private String title;

	private @ContentId UUID coverId;  	
	private @ContentLength Long coverLen;	
	private @MimeType String coverType;

	private @Embedded Chapter chapterOne = new Chapter();
	private @Embedded Chapter chapterTwo = new Chapter();
	...
}

@Embeddable
@Data
public class Chapter {

	// Content property 'video' storing the DVD video content
	private @ContentId UUID contentId;  	
	private @ContentLength Long contentLen;	
	private @MimeType String contentType;
}
----
====

Spring Content REST will export these associated Spring Resources under the URIs; `/books/{id}/cover`, `/books/{id}/chapterOne` and `/books/{id}/chapterTwo` and so on.

These endpoints can be found in the similarly named link relations in the Entity's
`application/hal+json` response:

====
[source, java]
----
  "_links" : {
    ...
    "cover" : {
      "href" : "http://localhost:8080/dvds/1/cover"
    },
    "chapterTwo" : {
      "href" : "http://localhost:8080/dvds/1/chapterTwo"
    },
    "chapterOne" : {
      "href" : "http://localhost:8080/dvds/1/chapterOne"
    }
----
====  

=== Nested Multiple Content Properties

Of course it is also possible to have multiple content properties on nested objects too, as in this example:-

====
[source, java]
----
@Entity
@Data
public class Book {
    private @Id @GeneratedValue Long id;
    private String title;

    private @ContentId UUID coverId;    
    private @ContentLength Long coverLen;   
    private @MimeType String coverType;

    private @Embedded Chapter chapterOne = new Chapter();
    private @Embedded Chapter chapterTwo = new Chapter();
    ...
}

@Embeddable
@Data
public class Chapter {

    // Content property 'video' storing the DVD video content
    private @ContentId UUID contentId;      
    private @ContentLength Long contentLen; 
    private @MimeType String contentType;

    private @ContentId UUID epigraphId;      
    private @ContentLength Long epigraphLen; 
    private @MimeType String epigraphType;
}
----
====

With nested multiple content properties Spring Content REST will export
 these associated Spring Resources under the URIs; `/books/{id}/cover`, 
 `/books/{id}/chapterOne/content`, `/books/{id}/chapterOne/epigraph`, 
 `/books/{id}/chapterTwo/content` and `/books/{id}/chapterTwo/epigraph`.

These endpoints can be found in the following link relations:

====
[source, java]
----
  "_links" : {
    ...
    "cover" : {
      "href" : "http://localhost:8080/dvds/1/cover"
    },
    "chapterOne/content" : {
      "href" : "http://localhost:8080/dvds/1/chapterOne/content"
    }
    "chapterOne/epigraph" : {
      "href" : "http://localhost:8080/dvds/1/chapterOne/epigraph"
    },
    "chapterTwo/content" : {
      "href" : "http://localhost:8080/dvds/1/chapterTwo/content"
    },
    "chapterTwo/epigraph" : {
      "href" : "http://localhost:8080/dvds/1/chapterTwo/epigraph"
    },
----
====  


=== Search

Exported content stores may be marked as `Searchable`.  Assuming the following content store interface:

====
[source, java]
----
  public interface DvdStore extends ContentStore<Dvd, UUID>, Searchable<UUID> {}
----
====

When the store is exported, Spring Content REST exposes a fulltext query resource for the `Searchable.search` methods.
These resources are exported to the URI `/dvds/searchContent`.  Method parameters can be supplied as query parameters:

====
[source, sh]
----
  curl -H 'Accept: application/hal+json'  http://localhost:8080/searchContent?queryString=foo
----
====

=== Default status codes

For the content resources exposed, we use a set of default status codes:

- 200 OK - for plain GET requests and POST and PUT requests that overwrite existing content resources
- 201 Created - for POST and PUT requests that create new content resources
- 204 No Content - for DELETE requests 
- 206 Partial Content - for range GET requests

=== Resource Discoverability

A core principle of HATEOAS is that Resources should be discoverable through the publication of links that point to the
available resources.  There are a few competing de-facto standards specifying how to represent links in JSON.  By default,
Spring Data REST uses HAL to render responses.  HAL defines links to be contained in a property of the returned document.

Resource discovery starts at the top level of the application.  By issuing a request to the root URL under which the
Spring Data REST application is deployed, the client can extract a set of links from the returned JSON object that
represent the next level of resources that are available to the client.

When enabled through `@Import(HypermediaConfiguration.class)` Spring Content REST will inject Store, Entity and Property
Resources links for both into the HAL responses created by Spring Data REST.

== The Store Resource

Spring Content REST exports Store Resources to `/{store}/**`.  The resource path and linkrel can be customized using the
`@StoreRestResource` annotation on the Store interface.

=== Supported HTTP Methods

Store Resources support `GET`, `PUT`, `POST`, and `DELETE`.  All other HTTP methods will cause a `405 Method Not
Allowed`.

==== GET

Returns the Resource's content

===== Supported media types

All content types except `application/json`

==== PUT/POST

Sets the Resources's content

===== Supported media types

All content types except `application/json`

==== DELETE

Removes the Resource's content

===== Supported media types

All content types except `application/json`

== The Entity Resource

Requests to `Store Resource` exist (partially) in the same URL space as Spring Data's Entity Resource.
When a single piece of content is associated with an entity then "shortcut" requests to `/{store}/{id}` 
will return content (or 404 if no content is set) instead of the entity's json.

This behavior can be customized by preventing the Store Resource from responding to shortcut requests
with certain media types using exclusions, or by completely disabling the Store Resource from responding 
to all shortcut requests, forcing full qualified requests only.  Note, this is likely to become the default
in future versions of Spring Content REST.

With Spring Boot 1.2 and later, you can customize the exclusions or disable shortcut requests entirely by 
setting either of the following properties in application.properties:

====
[source, java]
----
spring.content.rest.shortcut-request-mappings.excludes=<VERB>=<MEDIA_TYPE>[[,<MEDIA_TYPE>]:<VERB>=<MEDIA_TYPE>[,<MEDIA_TYPE>]]

spring.content.rest.shortcut-request-mappings.disabled=true|false
----
where:

- VERB is `GET`, `PUT`, `POST` or `DELETE`
- MEDIA_TYPE is any valid media type including `\*/*`
====

Or if you're not using Spring Boot, you can customize as follows:

====
[source, java]
----
@Configuration
class CustomContentRestMvcConfiguration {

  @Bean
  public ContentRestConfigurer contentRestConfigurer() {

    return new ContentRestConfigurer() {

      @Override
      public void configure(RestConfiguration config) {
        config.shortcutExclusions().exclude("GET", "*/*");
        
        // or
        // config.setShortcutLinks(false)
      }
    };
  }
}
----
====

== The Content Property Resource

Spring Content REST exports Property Resources to `/{store}/{id}/{contentPropertyPath}`.
The resource path and link relation prefix can be customized using the `@StoreRestResource` 
annotation on the Store interface.

=== Supported HTTP Methods

Property Resources support `GET`, `PUT`, `POST`, and `DELETE`.  All other HTTP methods will cause a `405 Method Not
Allowed`.

==== GET

Returns the Resource's content

===== Supported media types

All content types except `application/json`

==== PUT/POST

Sets the Resources's content

===== Supported media types

All content types except `application/json`

==== DELETE

Removes the Resource's content
