= Customizing Store Resources

== Configuring CORS

For security reasons, browsers prohibit AJAX calls to resources residing outside the current origin.  When working with
client-side HTTP requests issued by a browser you may want to enable specific HTTP resources to be accessible.

Spring Data Content supports Cross-Origin Resource Sharing (CORS) through Spring’s CORS support.

=== Store Interface CORS Configuration

You can add a @CrossOrigin annotation to your store interfaces to enable CORS for the whole store.  By default
@CrossOrigin allows all origins and HTTP methods:

====
[source, java]
----
@CrossOrigin
interface DvdStore extends ContentStore<Dvd, UUID> {}
----
====

In the above example CORS support is enabled for the whole DvdStore.  @CrossOrigin also provides attributes to perform
more granular configuration.

====
[source,java]
----
@CrossOrigin(origins = "http://mydomain.com",
  methods = { RequestMethod.GET, RequestMethod.POST, RequestMethod.DELETE },
  maxAge = 3600)
interface DvdStore extends ContentStore<Dvd, UUID> {}
----
====

This example enables CORS support for the whole DvdStore providing one origin, restricted to GET, POST and DELETE
methods with a max age of 3600 seconds.

=== Global CORS Configuration

In addition to fine-grained, annotation-based configuration, you probably want to define some global CORS configuration
as well. This is similar to Spring Web MVC’S CORS configuration but can be declared within Spring Content REST and
combined with fine-grained @CrossOrigin configuration. By default, all origins and GET, HEAD, and POST methods are
allowed.

The following example sets up the same CORS configuration but as a global configuration:

====
[source,java]
----
@Configuration
public class SpringContentRestCustomization {

	@Bean
	private ContentRestConfigurer contentRestConfigurer() {

		return new ContentRestConfigurer() {
			@Override
			public void configure(RestConfiguration config) {
				config.getCorsRegistry().addMapping("/dvds/**")
						.allowedMethods("GET", "POST", "DELETE")
						.allowedOrigins("http://mydomain.com")
						.maxAge(3600);
			}
		};
	}
}
----
====
