== Store Links

For each Spring Resource associated with an Entity, Spring Content REST will generate a fully-qualified link and inject it into the Entity's 
Spring Data REST HAL response. 

Given the following domain model, Repository and Store:

====
[source, java]
----
  @Entity
  public class Dvd {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @ContentId
    private UUID videoId;

    @ContentLength
    private Long videoLength;

    @MimeType
    private String videoMimeType;

    // getters and setters
  }

  public interface DvdRepository extends CrudRepository<Dvd, Long> {}

  public interface DvdStore extends ContentStore<Dvd, UUID> {}
----
====

Spring Content REST will inject the following link:

====
[source, java]
----
  "_links" : {
    "self" : {
      ...
    },
    "dvd" : {
      ...
    },
    "video" : {
      "href" : "http://localhost:8080/dvds/1/video"
    }
  }
----
====

Where the linkrel is named after the content property and the link URI is the fully-qualified URI of that content property.

=== Customizing the link relation

Sometimes it can be useful to configure the linkrel for a content property.  This is done by specifying the `linkRel` attribute on 
the StoreRestResource, as follows:

====
[source, java]
----
  @StoreRestResource(linkRel="custom-linkrel")
  public interface DvdStore extends ContentStore<Dvd, UUID> {}
----
====

This will result in the following linkrel instead:

====
[source, java]
----
 "_links" : {
    "self" : {
      ...
    },
    "dvd" : {
      ...
    },
    "custom-linkrel/video" : {
      "href" : "http://localhost:8080/dvds/1/video"
    }
  }
----
====

The linkrel can be further customized by specifying the `linkRel` attribute on
the `@RestResource` placed on any field contributing to the path up-to and including the
@ContentId field, as follows:

====
[source, java]
----
  @Entity
  public class Dvd {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @RestResource(linkRel="movie")
    @ContentId
    private UUID videoId;

    @ContentLength
    private Long videoLength;

    @MimeType
    private String videoMimeType;

    // getters and setters
  }

  public interface DvdRepository extends CrudRepository<Dvd, Long> {}

  @StoreRestResource(linkRel="custom-linkrel")
  public interface DvdStore extends ContentStore<Dvd, UUID> {}
----
====

Resulting in the following lnkrel:-

====
[source, java]
----
 "_links" : {
    "self" : {
      ...
    },
    "dvd" : {
      ...
    },
    "custom-linkrel/movie" : {
      "href" : "http://localhost:8080/dvds/1/video"
    }
  }
----
====

=== Customizing the link

In addition, the link itself can also be customized by specifying the `path` attribute on
the `@RestResource` placed on any field contributing to the path up-to and including the
@ContentId field, as follows:

====
[source, java]
----
  @Entity
  public class Dvd {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @RestResource(linkRel="movie", path="movie")
    @ContentId
    private UUID videoId;

    @ContentLength
    private Long videoLength;

    @MimeType
    private String videoMimeType;

    // getters and setters
  }

  public interface DvdRepository extends CrudRepository<Dvd, Long> {}

  @StoreRestResource(linkRel="custom-linkrel")
  public interface DvdStore extends ContentStore<Dvd, UUID> {}
----
====

Resulting in the following lnk:-

====
[source, java]
----
 "_links" : {
    "self" : {
      ...
    },
    "dvd" : {
      ...
    },
    "custom-linkrel/movie" : {
      "href" : "http://localhost:8080/dvds/1/movie"
    }
  }
----
====